const SOURCE_MASKS = 'https://www.poderjudicial.es/cgpj/es/Poder-Judicial/Tribunal-Supremo/Oficina-de-Comunicacion/Notas-de-prensa/El-instructor-del-Tribunal-Supremo-abre-juicio-oral-al-exministro-Abalos--su-exasesor-Koldo-Garcia-y-el-empresario-Aldama-por-la-contratacion-irregular-de-mascarillas-durante-la-pandemia-de-COVID';
const SOURCE_MASKS_TRIAL = 'https://www.poderjudicial.es/cgpj/es/Poder-Judicial/Tribunal-Supremo/Oficina-de-Comunicacion/Notas-de-prensa/El-Tribunal-Supremo-rechaza-todas-las-cuestiones-previas-planteadas-por-las-defensas-del-exministro-Jose-Luis-Abalos-y-su-exasesor-Koldo-Garcia-y-senala-el-7-de-abril-el-inicio-del-juicio';
const SOURCE_MASKS_SENTENCE = 'https://www.europapress.es/nacional/noticia-supremo-condena-abalos-24-anos-carcel-19-koldo-aldama-caso-mascarillas-20260622121517.html';
const SOURCE_MASKS_NULLITY = 'https://elpais.com/espana/2026-07-15/abalos-pide-al-supremo-que-anule-su-condena-porque-su-caso-debio-juzgarse-en-la-audiencia-nacional.html';
const SOURCE_WORKS = 'https://www.poderjudicial.es/portal/site/cgpj/menuitem.65d2c4456b6ddb628e635fc1dc432ea0/?lang_choosen=en&perfil=0&vgnextchannel=ccc9c38cb605c210VgnVCM100000cb34e20aRCRD&vgnextfmt=default&vgnextlocale=en&vgnextoid=4c6dd75e42f1c910VgnVCM1000004648ac0aRCRD';
const SOURCE_CERDAN = 'https://www.poderjudicial.es/cgpj/es/Poder-Judicial/Tribunal-Supremo/Oficina-de-Comunicacion/Notas-de-prensa/El-Tribunal-Supremo-confirma-la-prision-provisional-de-Santos-Cerdan-por-riesgo-de-destruccion-de-pruebas-ante-indicios-de-su--papel-directivo--en-la-trama-que-se-investiga';
const SOURCE_ERE_TC = 'https://hj.tribunalconstitucional.es/HJ/es/Resolucion/Show/31221';
const SOURCE_ERE_PENDING = 'https://www.poderjudicial.es/cgpj/ca/Poder-Judicial/Tribunals-Superiors-de-Justicia/TSJ-Andalusia--Ceuta-i-Melilla/Sala-de-premsa/Comunicats-de-premsa/La-Audiencia-de-Sevilla-acuerda-plantear-una-cuestion-prejudicial-ante-el-TJUE-tras-las-sentencias-del-Tribunal-Constitucional-sobre-el-caso-ERE';
const SOURCE_INVER_FUMAPA = 'https://www.poderjudicial.es/cgpj/es/Poder-Judicial/Tribunal-Supremo/Noticias-Judiciales/El-Tribunal-Supremo-reduce-de-3-a-2-anos-de-prision-una-condena-al-expresidente-de-Invercaria-en-aplicacion-de-la-reforma-del-delito-de-malversacion';
const SOURCE_INVER_TATIS = 'https://www.poderjudicial.es/cgpj/en/Judiciary/Supreme-Court/Pressroom/Press-Archive/El-Tribunal-Supremo-confirma-la-condena-al-expresidente-de-Invercaria-por-prevaricacion-y-malversacion-por-la-concesion-irregular-de-un-prestamo-de-100-000-euros';
const SOURCE_INVER_SALARIES = 'https://www.poderjudicial.es/portal/site/cgpj/menuitem.65d2c4456b6ddb628e635fc1dc432ea0/?perfil=0&vgnextchannel=ae0d512f8032a210VgnVCM100000cb34e20aRCRD&vgnextfmt=formato3&vgnextlocale=en&vgnextoid=43bd872a75a02910VgnVCM1000004648ac0aRCRD';
const SOURCE_FAFFE = 'https://www.poderjudicial.es/cgpj/gl/Poder-Xudicial/Tribunais-Superiores-de-Xustiza/TSX-Andalucia--Ceuta-e-Melilla/Noticias-Xudicial-TSX-Andalucia--Ceuta-e-Melilla/La-Audiencia-de-Sevilla-condena-a-seis-anos-de-carcel-al-exdirector-de-la-Faffe-por-la-utilizacion-de-tarjetas-bancarias-de-la-fundacion-en-prostibulos';
const SOURCE_FAFFE_OPEN = 'https://www.poderjudicial.es/cgpj/en/Judiciary/High-Courts-of-Justice/HCJ-Andalusia--Ceuta-and-Melilla/Pressroom/Press-Archive/El-Juzgado-de-Instruccion-numero-6-de-Sevilla-cita-a-declarar-a-21-investigados-en-la-causa-de-la-Faffe-y-prorroga-otros-seis-meses-el-plazo-de-instruccion-del-procedimiento';
const SOURCE_MERCA = 'https://www.poderjudicial.es/portal/site/cgpj/menuitem.65d2c4456b6ddb628e635fc1dc432ea0/?lang_choosen=en&perfil=3&vgnextchannel=05bc3da6cbe0a210VgnVCM1000006f48ac0aRCRD&vgnextfmt=default&vgnextlocale=en&vgnextoid=fa76ca01e9066410VgnVCM1000006f48ac0aRCRD';
const SOURCE_FILESA_NAVARRO = 'https://www.boe.es/diario_boe/txt.php?id=BOE-T-2001-12756';
const SOURCE_FILESA_SALA = 'https://www.boe.es/diario_boe/txt.php?id=BOE-T-2001-12757';
const SOURCE_PRETORIA_TS = 'https://www.poderjudicial.es/cgpj/es/Poder-Judicial/Tribunal-Supremo/Noticias-Judiciales/El-Tribunal-Supremo-confirma-la-pena-de-cinco-anos-y-ocho-meses-de-prision-al-exalcalde-de-Santa-Coloma-de-Gramenet-por-la--operacion-Pretoria--';
const SOURCE_PRETORIA_AN = 'https://www.poderjudicial.es/cgpj/es/Poder-Judicial/Audiencia-Nacional/Oficina-de-Comunicacion/Notas-de-prensa/La-Audiencia-Nacional-condena-a-penas-de-hasta-7-anos-a-los-once-acusados-en-la--operacion-Pretoria-';
const SOURCE_MEDIADOR_CLOSE = 'https://www.poderjudicial.es/cgpj/es/Poder-Judicial/Noticias-Judiciales/La-magistrada-del--caso-Mediador--finaliza-la-instruccion-';
const SOURCE_MEDIADOR_NAMES = 'https://www.poderjudicial.es/stfls/TRIBUNALES%20SUPERIORES%20DE%20JUSTICIA/TSJ%20Canarias/MEMORIA/MEMORIA%202023-23052024.pdf';
const SOURCE_LINARES = 'https://www.poderjudicial.es/portal/site/cgpj/menuitem.65d2c4456b6ddb628e635fc1dc432ea0/?perfil=0&vgnextchannel=ea1732cd1ddaa210VgnVCM100000cb34e20aRCRD&vgnextfmt=default&vgnextlocale=es_ES&vgnextoid=da942356910d7910VgnVCM1000004648ac0aRCRD';
const SOURCE_COURSES_DELPHI = 'https://www.poderjudicial.es/cgpj/en/Judiciary/Pressroom/News-archive/El-juez-continua-el-procedimiento-contra-un-exconsejero-de-la-Junta-de-Andalucia-y-otros-dos-investigados-en-una-pieza-separada-de-la-causa-de-la-formacion-por-la-contratacion--ficticia--de-extrabajadores-de-Delphi';
const SOURCE_RECIO_ID = 'https://www.juntadeandalucia.es/boja/2010/153/32';
const SOURCE_COURSES_ARCHIVE = 'https://www.poderjudicial.es/cgpj/en/Judiciary/Pressroom/News-archive/El-juez-archiva-la-causa-contra-el-exalcalde-de-Granada-y-otros-nuevo-investigados-por-la-contratacion-de-servicios-para-realizar-labores-de-inspeccion-de-Cursos-de-Formacion-en-Economia-Social';
const SOURCE_CUENCA_ID = 'https://transparencia.granada.org/publico/pagina/_GRAN_504';
const SOURCE_FITONOVO_AN = 'https://www.poderjudicial.es/portal/site/cgpj/menuitem.65d2c4456b6ddb628e635fc1dc432ea0/?lang_choosen=gl&vgnextchannel=3e6ff2175f35c210VgnVCM100000cb34e20aRCRD&vgnextfmt=default&vgnextlocale=gl&vgnextoid=beaa129ec9b95810VgnVCM1000004648ac0aRCRD';
const SOURCE_FITONOVO_TS = 'https://www.poderjudicial.es/search/documento/AN/11317597/Cohecho/20250527';
const SOURCE_MAREA_TS = 'https://www.poderjudicial.es/portal/site/cgpj/menuitem.65d2c4456b6ddb628e635fc1dc432ea0/?lang_choosen=ca&vgnextchannel=ae0d512f8032a210VgnVCM100000cb34e20aRCRD&vgnextfmt=default&vgnextlocale=ca&vgnextoid=a3d1e11c1983d610VgnVCM1000006f48ac0aRCRD';
const SOURCE_MAREA_AP = 'https://www.poderjudicial.es/portal/site/cgpj/menuitem.65d2c4456b6ddb628e635fc1dc432ea0/?perfil=0&vgnextchannel=05bc3da6cbe0a210VgnVCM100000cb34e20aRCRD&vgnextfmt=default&vgnextlocale=eu&vgnextoid=0670ee6709c3e510VgnVCM1000006f48ac0aRCRD';
const SOURCE_CIEMPOZUELOS = 'https://www.poderjudicial.es/cgpj/en/Judiciary/Supreme-Court/Pressroom/Press-Archive/El-Tribunal-Supremo-condena-a-un-ano-de-prision-a-dos-exalcaldes-de-Ciempozuelos--Madrid--por-falsedad-en-documento-mercantil';
const SOURCE_ALICANTE_TS = 'https://www.poderjudicial.es/cgpj/es/Poder-Judicial/Tribunal-Supremo/Oficina-de-Comunicacion/Notas-de-prensa/El-Tribunal-Supremo-confirma-la-comision-de-delito-de-prevaricacion-por-el-exalcalde-de-Alicante-en-dos-causas';
const SOURCE_ECHAVARRI_ID = 'https://www.alicante.es/es/noticias/alcalde-presenta-retrato-gabriel-echavarri-y-ocupa-lugar-galeria-ediles';
const SOURCE_MALAYA_AP = 'https://www.poderjudicial.es/portal/site/cgpj/menuitem.65d2c4456b6ddb628e635fc1dc432ea0/?lang_choosen=en&perfil=1&vgnextchannel=14c6939ae5821310VgnVCM1000006f48ac0aRCRD&vgnextfmt=default&vgnextlocale=en&vgnextoid=a5f4693235281410VgnVCM1000006f48ac0aRCRD';
const SOURCE_MALAYA_TS = 'https://www.poderjudicial.es/cgpj/es/Poder-Judicial/Tribunal-Supremo/Oficina-de-Comunicacion/Archivo-de-notas-de-prensa/El-TS-confirma-la-mayoria-de-las-penas-del-caso-Malaya-y-eleva-de-11-a-17-anos-la-condena-a-Juan-Antonio-Roca';
const SOURCE_GARCIA_PSOE = 'https://www.marbella.es/actualidad/noticias/el-ayuntamiento-prosigue-adelante-con-la-bateria-de-medidas-judiciales-para-recuperar-los-bienes-que-fueron-expoliados-por-anteriores-gobiernos-locales.html';
const SOURCE_CONTROL_MARBELLA = 'https://www.boe.es/diario_boe/txt.php?id=BOE-B-2015-36649';
const SOURCE_ASTAPA_OFFICIAL = 'https://www.poderjudicial.es/stfls/CGPJ/%C3%81REA%20DE%20TRANSPARENCIA/PROCESOS%20SELECTIVOS/FICHEROS/20250408%20Presidencia%20AP%20M%C3%A1laga%20-%20PA%20Madro%C3%B1al%20Navarro%2C%20Jes%C3%BAs%20Manuel.pdf';
const SOURCE_ASTAPA_EFE = 'https://efe.com/andalucia/2024-11-08/el-caso-astapa-termina-con-31-absueltos-y-penas-menores-como-la-suspension-del-exalcalde/';
const SOURCE_ASTAPA_APPEAL = 'https://www.andaluciainformacion.es/articulo/malaga/la-fiscalia-no-recurre-la-sentencia-del-caso-astapa-y-se-declara-firme-para-31-acusados/20250117160256938118.amp.html';
const SOURCE_AZUD_CGPJ = 'https://www.poderjudicial.es/cgpj/en/Judiciary/High-Courts-of-Justice/HCJ-Valencian-Community/Pressroom/Press-Archive/La-juez-del--caso-Azud--decreta-prision-para-el-exvicealcalde-de-Valencia--el-exsubdelegado-del-Gobierno-y-tres-empresarios-';
const SOURCE_RUBIO_AFFILIATION = 'https://www.poderjudicial.es/portal/site/cgpj/menuitem.65d2c4456b6ddb628e635fc1dc432ea0/?lang_choosen=eu&vgnextchannel=fb8f825dd79f0310VgnVCM1000006f48ac0aRCRD&vgnextfmt=default&vgnextlocale=eu&vgnextoid=fd586bc54ee58710VgnVCM1000006f48ac0aRCRD';
const SOURCE_AZUD_UCO = 'https://www.lavanguardia.com/local/valencia/20250621/10813029/informe-uco-senala-exportavoz-pspv-valencia-cobro-comisiones.html';
const SOURCE_PLUS_ULTRA_AUTO = 'https://www.primicias.ec/uploads/files/2026/05/20/Auto-Rodriguez-Zapatero.pdf';
const SOURCE_PLUS_ULTRA_DAUGHTERS = 'https://www.elnacional.cat/uploads/s1/58/81/44/56/2026-6-18-auto-investigacion-hijas-y-secretaria-rodriguiez-zapatero.pdf';
const SOURCE_PLUS_ULTRA_EFE = 'https://efe.com/espana/2026-06-18/hijas-zapatero-imputadas-plus-ultra/';
const SOURCE_BEGONA_EFE = 'https://efe.com/espana/2026-07-18/caso-begona-gomez-pasos/';
const SOURCE_DAVID_SENTENCE = 'https://descargables.elpais.com/sentencia-condena-david-sanchez-miguel-angel-gallardo.pdf';
const SOURCE_ROLDAN_TC = 'https://www.boe.es/diario_boe/txt.php?id=BOE-A-2011-13301';
const SOURCE_ROLDAN_RTVE = 'https://www.rtve.es/noticias/20220324/muere-luis-roldan/2321691.shtml';
const SOURCE_ROLDAN_LIQUIDATION = 'https://elpais.com/elpais/2005/01/13/actualidad/1105607820_850215.html';
const SOURCE_URRALBURU_TS = 'https://www.poderjudicial.es/stfls/CGPJ/CENDOJ/PUBLICACIONES/REVISTA%20PJ%20-%205%C2%AA%20%C3%A9poca/FICHERO/PJ11091.pdf';
const SOURCE_URRALBURU_HISTORY = 'https://www.eldiario.es/navarra/25-anos-condena-socialista-urralburu-primer-presidente-autonomico-encarcelado-cobro-comisiones_1_10494636.amp.html';

const cases = [
  { id:'mascarillas', name:'Caso mascarillas', subtitle:'Contratación durante la pandemia', color:'#7fe7f2', status:'revision', x:0, y:-65, z:55, milestoneDate:'2026-06-22', milestone:'El Supremo dicta sentencia; Ábalos solicita su nulidad' },
  { id:'obras', name:'Pieza de obras públicas', subtitle:'Adjudicaciones y presuntas comisiones', color:'#f2b84b', status:'investigacion', x:185, y:95, z:-70, milestoneDate:'2026-02-02', milestone:'La pieza se remite a la Audiencia Nacional' },
  { id:'ere', name:'ERE · pieza específica', subtitle:'Ayudas sociolaborales de Andalucía', color:'#6c8cff', status:'revision', x:-190, y:100, z:-95, milestoneDate:'2025-07-15', milestone:'La Audiencia eleva una cuestión prejudicial al TJUE' },
  { id:'invercaria', name:'Caso Invercaria', subtitle:'Préstamos e incrementos retributivos', color:'#ff6f7d', status:'condena', x:245, y:-145, z:-125, milestoneDate:'2024-09-19', milestone:'El Supremo dicta condena en la pieza de retribuciones' },
  { id:'faffe', name:'Caso FAFFE', subtitle:'Tarjetas y fondos de la fundación', color:'#d691ff', status:'revision', x:-250, y:-140, z:-145, milestoneDate:'2023-09-21', milestone:'La Audiencia dicta condena recurrible en la pieza de tarjetas' },
  { id:'mercasevilla', name:'Caso Mercasevilla', subtitle:'Solicitud de soborno en escuela de hostelería', color:'#64d18f', status:'condena', x:20, y:215, z:-175, milestoneDate:'2014-06-03', milestone:'El Supremo confirma dos condenas y anula una tercera' },
  { id:'filesa', name:'Caso Filesa', subtitle:'Financiación electoral mediante sociedades', color:'#ef7ca8', status:'condena', x:-365, y:35, z:-205, milestoneDate:'2001-06-04', milestone:'El Constitucional resuelve los recursos de amparo' },
  { id:'pretoria', name:'Operación Pretoria', subtitle:'Operaciones urbanísticas en Cataluña', color:'#f0cf67', status:'condena', x:365, y:30, z:-205, milestoneDate:'2020-12-18', milestone:'El Supremo confirma y ajusta las condenas' },
  { id:'mediador', name:'Caso Mediador', subtitle:'Presunta trama político-empresarial en Canarias', color:'#42c7aa', status:'procesamiento', x:0, y:-210, z:-210, milestoneDate:'2026-02-12', milestone:'Finaliza la instrucción contra 23 personas' },
  { id:'linares', name:'Sobresueldos de Linares', subtitle:'Fondos del grupo municipal socialista', color:'#ff986a', status:'condena', x:-230, y:-155, z:-100, milestoneDate:'2025-07-03', milestone:'El Supremo confirma la condena por malversación' },
  { id:'cursos_delphi', name:'Formación · pieza Delphi', subtitle:'Subvención a FUECA para extrabajadores', color:'#40b8ff', status:'procesamiento', x:285, y:185, z:-70, milestoneDate:'2025-01-14', milestone:'El juzgado acuerda continuar por procedimiento abreviado' },
  { id:'cursos_inspeccion', name:'Formación · inspecciones', subtitle:'Contratos para control de cursos', color:'#8aa0b5', status:'archivo', x:-285, y:185, z:-70, milestoneDate:'2023-09-27', milestone:'El juzgado archiva la causa respecto de diez investigados' },
  { id:'fitonovo', name:'Caso Fitonovo · Sevilla', subtitle:'Adjudicaciones y dádivas a funcionarios', color:'#f07bc1', status:'condena', x:270, y:-35, z:-90, milestoneDate:'2025-04-24', milestone:'El Supremo resuelve la casación de las piezas enjuiciadas' },
  { id:'marea', name:'Caso Marea', subtitle:'Contratos y dádivas en el Principado de Asturias', color:'#33d0c5', status:'condena', x:0, y:140, z:-80, milestoneDate:'2019-09-13', milestone:'El Supremo confirma y ajusta las condenas' },
  { id:'ciempozuelos', name:'Caso Ciempozuelos', subtitle:'Contrato falso remitido a un banco de Andorra', color:'#ffb15c', status:'condena', x:-100, y:-140, z:-80, milestoneDate:'2016-06-02', milestone:'El Supremo condena a los dos exalcaldes por falsedad mercantil' },
  { id:'alicante', name:'Prevaricación en Alicante', subtitle:'Contratación fraccionada y cese de una funcionaria', color:'#b9d65e', status:'condena', x:300, y:105, z:-45, milestoneDate:'2022-05-11', milestone:'El Supremo confirma dos condenas por prevaricación' },
  { id:'malaya', name:'Operación Malaya', subtitle:'Corrupción urbanística en Marbella', color:'#ff6a9d', status:'condena', x:410, y:-150, z:-115, milestoneDate:'2015-07-27', milestone:'El Supremo confirma la mayoría de las penas y ajusta condenas' },
  { id:'control_marbella', name:'Control de Servicios · Marbella', subtitle:'Reintegro por alcance en fondos de una sociedad municipal', color:'#d8a64d', status:'revision', x:390, y:-230, z:-35, milestoneDate:'2015-11-16', milestone:'El Tribunal de Cuentas declara un alcance de 71.285,60 €' },
  { id:'astapa', name:'Caso Astapa', subtitle:'Procedimiento urbanístico de Estepona', color:'#ff875c', status:'revision', x:-430, y:-220, z:-80, milestoneDate:'2024-11-08', milestone:'La Audiencia dicta sentencia; parte del fallo queda recurrida' },
  { id:'azud', name:'Caso Azud', subtitle:'Operaciones urbanísticas y contratos en Valencia', color:'#6bd4ff', status:'investigacion', x:450, y:180, z:-85, milestoneDate:'2025-06-21', milestone:'Un informe de la UCO atribuye una horquilla de comisiones investigadas' },
  { id:'plus_ultra', name:'Caso Plus Ultra', subtitle:'Rescate público y presunto tráfico de influencias', color:'#ffcf5c', status:'investigacion', x:10, y:-310, z:-105, milestoneDate:'2026-06-18', milestone:'El instructor amplía las diligencias a las hijas de Zapatero' },
  { id:'begona_gomez', name:'Caso Begoña Gómez', subtitle:'Actividad profesional y uso de recursos públicos', color:'#ff7aa8', status:'procesamiento', x:520, y:-55, z:-95, milestoneDate:'2026-07-16', milestone:'La Audiencia ordena continuar por dos presuntos delitos' },
  { id:'david_sanchez', name:'Caso David Sánchez', subtitle:'Creación y adaptación de un puesto en Badajoz', color:'#9db5ff', status:'revision', x:-520, y:25, z:-90, milestoneDate:'2026-07-14', milestone:'Condena de primera instancia recurrible por prevaricación' },
  { id:'roldan', name:'Caso Roldán', subtitle:'Fondos reservados, comisiones y contratos de la Guardia Civil', color:'#ff5f6d', status:'condena', x:-570, y:-150, z:-155, milestoneDate:'1999-12-21', milestone:'El Supremo eleva a 31 años la pena de prisión' },
  { id:'urralburu', name:'Caso Urralburu', subtitle:'Comisiones por adjudicaciones de obra pública en Navarra', color:'#cda8ff', status:'condena', x:-590, y:175, z:-165, milestoneDate:'2001-03-28', milestone:'El Supremo fija la condena firme por cohecho' }
];

const sharedMasksSources = [
  { title:'Auto de apertura de juicio oral', date:'Tribunal Supremo · 11 DIC 2025', url:SOURCE_MASKS },
  { title:'Sentencia y fallo individualizado', date:'Tribunal Supremo / Europa Press · 22 JUN 2026', url:SOURCE_MASKS_SENTENCE },
  { title:'Incidente de nulidad promovido por Ábalos', date:'Tribunal Supremo / EL PAÍS · 15 JUL 2026', url:SOURCE_MASKS_NULLITY }
];
const sharedWorksSources = [
  { title:'Remisión de la pieza de obras a la Audiencia Nacional', date:'Tribunal Supremo · 02 FEB 2026', url:SOURCE_WORKS }
];
const ereSources = [
  { title:'STC 99/2024: amparo de Manuel Chaves', date:'Tribunal Constitucional · 16 JUL 2024', url:SOURCE_ERE_TC },
  { title:'Cuestión prejudicial al TJUE y suspensión', date:'Audiencia Provincial de Sevilla · 15 JUL 2025', url:SOURCE_ERE_PENDING }
];

const caseProfiles = {
  mascarillas:{phase:'Sentencia del Tribunal Supremo; nulidad solicitada',phaseNote:'Ábalos y Koldo fueron condenados por organización criminal, cohecho, tráfico de influencias y malversación; Aldama, por organización criminal y cohecho. Los tres fueron absueltos de otras acusaciones. Ábalos ha promovido un incidente de nulidad como paso previo al amparo.',money:'430.298 €',moneyLabel:'GANANCIAS DE COHECHO OBJETO DE COMISO',moneyNote:'Comiso conjunto acordado en la sentencia: 340.000 € en pagos mensuales y 90.298 € en rentas de viviendas. No se duplica en las fichas personales ni equivale al volumen de contratos.',sources:sharedMasksSources},
  obras:{phase:'Instrucción en la Audiencia Nacional',phaseNote:'La pieza sobre adjudicaciones de obra pública fue remitida al Juzgado Central de Instrucción nº 2.',money:'≈ 1 M€',moneyLabel:'FLUJO INVESTIGADO EN LA TRAMA',moneyNote:'La resolución cita además 537,27 M€ de obras adjudicadas; ese volumen contractual no equivale a perjuicio público.',sources:[{title:'Remisión a la Audiencia Nacional',date:'Tribunal Supremo · 02 FEB 2026',url:SOURCE_WORKS},{title:'Auto sobre indicios y flujo investigado',date:'Tribunal Supremo · 23 JUL 2025',url:SOURCE_CERDAN}]},
  ere:{phase:'Revisión suspendida por cuestión prejudicial',phaseNote:'La Audiencia de Sevilla suspendió la ejecución de los mandatos del Constitucional hasta la respuesta del TJUE.',money:'No consolidable',moneyLabel:'CUANTÍA DE LA PIEZA',moneyNote:'No se muestra como “robado” el presupuesto agregado del programa; las responsabilidades deben analizarse por persona y pieza.',sources:ereSources},
  invercaria:{phase:'Varias piezas con resultados distintos',phaseNote:'Existen condenas firmes y absoluciones en función del préstamo o actuación enjuiciada.',money:'Por pieza',moneyLabel:'RESPONSABILIDAD ECONÓMICA',moneyNote:'No se suman préstamos, retribuciones e indemnizaciones de causas diferentes como si fueran un único perjuicio.',sources:[{title:'Pieza Aceitunas Tatis',date:'Tribunal Supremo · 20 OCT 2022',url:SOURCE_INVER_TATIS},{title:'Pieza Fumapa',date:'Tribunal Supremo · 14 MAR 2024',url:SOURCE_INVER_FUMAPA},{title:'Pieza de retribuciones',date:'Tribunal Supremo · 19 SEP 2024',url:SOURCE_INVER_SALARIES}]},
  faffe:{phase:'Condena recurrible y otras piezas abiertas',phaseNote:'La pieza de tarjetas produjo una condena de primera instancia; una causa más amplia seguía en instrucción en 2025.',money:'32.566 €',moneyLabel:'GASTO CON TARJETAS EN LA PIEZA',moneyNote:'Importe total de gastos declarado probado en la pieza de tarjetas; parte fue devuelta y las indemnizaciones son distintas.',sources:[{title:'Sentencia de la pieza de tarjetas',date:'Audiencia Provincial de Sevilla · 21 SEP 2023',url:SOURCE_FAFFE},{title:'Instrucción de otra pieza',date:'Juzgado de Instrucción nº 6 · 04 FEB 2025',url:SOURCE_FAFFE_OPEN}]},
  mercasevilla:{phase:'Sentencias firmes y una absolución',phaseNote:'El Supremo confirmó las condenas de dos responsables y anuló la de Antonio Rivas.',money:'450.000 €',moneyLabel:'SOBORNO SOLICITADO',moneyNote:'Solicitud de soborno, no gasto público ejecutado. La escuela estaba vinculada a una subvención de 900.000 €.',sources:[{title:'Resolución del Tribunal Supremo',date:'Tribunal Supremo · 03 JUN 2014',url:SOURCE_MERCA}]},
  filesa:{phase:'Sentencias firmes con amparos posteriores',phaseNote:'El Constitucional resolvió individualmente los recursos; en el caso de Sala anuló solo la condena por falsedad.',money:'258.827.765 ptas',moneyLabel:'CUOTA FISCAL COMPARTIDA',moneyNote:'Responsabilidad fiscal histórica compartida en una de las condenas; no equivale al total de financiación ni a apropiación personal.',sources:[{title:'STC 123/2001 · Carlos Navarro',date:'Tribunal Constitucional / BOE · 04 JUN 2001',url:SOURCE_FILESA_NAVARRO},{title:'STC 124/2001 · José María Sala',date:'Tribunal Constitucional / BOE · 04 JUN 2001',url:SOURCE_FILESA_SALA}]},
  pretoria:{phase:'Condenas firmes tras casación',phaseNote:'El Supremo confirmó la condena del exalcalde y modificó parcialmente la del exdiputado del PSC.',money:'5.886.925,66 €',moneyLabel:'GANANCIAS ILÍCITAS OBJETO DE COMISO',moneyNote:'Total relativo a las tres operaciones enjuiciadas; no representa automáticamente un desembolso público municipal.',sources:[{title:'Sentencia de instancia',date:'Audiencia Nacional · 30 ABR 2018',url:SOURCE_PRETORIA_AN},{title:'Resolución de casación',date:'Tribunal Supremo · 18 DIC 2020',url:SOURCE_PRETORIA_TS}]},
  mediador:{phase:'Procedimiento abreviado tras finalizar la instrucción',phaseNote:'La causa continúa contra 23 personas. La nota pública enumera delitos de forma conjunta, no individual por encausado.',money:'13.500 €',moneyLabel:'EFECTIVO ENTREGADO EN LA PRIMERA PIEZA JUZGADA',moneyNote:'Suma de cinco entregas declaradas probadas en una pieza ya juzgada; no cuantifica el conjunto del procedimiento principal.',sources:[{title:'Finalización de la instrucción principal',date:'Tribunal de Instancia · 12 FEB 2026',url:SOURCE_MEDIADOR_CLOSE},{title:'Primera pieza juzgada',date:'Audiencia Provincial de Tenerife · 04 MAR 2026',url:'https://www.poderjudicial.es/portal/site/cgpj/menuitem.65d2c4456b6ddb628e635fc1dc432ea0/?vgnextchannel=ea1732cd1ddaa210VgnVCM100000cb34e20aRCRD&vgnextfmt=default&vgnextlocale=es_ES&vgnextoid=81de0713366bc910VgnVCM1000004648ac0aRCRD'}]},
  linares:{phase:'Sentencia firme',phaseNote:'El Tribunal Supremo confirmó tres años de prisión y siete de inhabilitación por malversación de caudales públicos.',money:'125.377 €',moneyLabel:'FONDOS PÚBLICOS DESVIADOS',moneyNote:'Sobresueldos cobrados desde las cuentas del grupo municipal socialista. La sentencia indica que actuó sin autorización ni conocimiento del grupo.',sources:[{title:'Confirmación de la condena por el Tribunal Supremo',date:'Tribunal Supremo · 03 JUL 2025',url:SOURCE_LINARES}]},
  cursos_delphi:{phase:'Procedimiento abreviado',phaseNote:'El instructor acordó continuar la causa contra el exconsejero y otras dos personas por si los hechos fueran constitutivos de fraude de subvenciones, prevaricación y malversación.',money:'20.236.626,57 €',moneyLabel:'SUBVENCIÓN EXAMINADA',moneyNote:'Importe concedido a FUECA. Es el volumen de la subvención investigada, no una declaración de perjuicio ni de apropiación personal.',sources:[{title:'Auto de procedimiento abreviado en la pieza Delphi',date:'Juzgado de Instrucción nº 6 de Sevilla · 14 ENE 2025',url:SOURCE_COURSES_DELPHI}]},
  cursos_inspeccion:{phase:'Archivo respecto de diez investigados',phaseNote:'El auto archivó la causa frente al exalcalde de Granada y otras nueve personas; abrió juicio oral respecto de nueve acusados distintos que no se incorporan todavía sin identificación suficiente.',money:'24.412 €',moneyLabel:'CONTRATOS EXAMINADOS',moneyNote:'Suma de dos contratos menores citados en el auto. Respecto de Francisco Cuenca, la causa quedó archivada y la cuantía penalmente atribuible es 0 €.',sources:[{title:'Archivo y apertura de juicio para grupos distintos',date:'Juzgado de Instrucción nº 6 de Sevilla · 27 SEP 2023',url:SOURCE_COURSES_ARCHIVE}]},
  fitonovo:{phase:'Condenas personales y absolución de las formaciones políticas',phaseNote:'La Audiencia Nacional condenó a diez personas en las piezas de Sevilla y Algeciras y absolvió expresamente al PSOE e IU como partícipes a título lucrativo.',money:'No acreditado',moneyLabel:'PERJUICIO PÚBLICO CUANTIFICADO',moneyNote:'El Supremo indica que no existe prueba pericial suficiente para identificar el lucro cesante reclamado como perjuicio. No se presenta el volumen contractual como dinero robado.',sources:[{title:'Sentencia de la Audiencia Nacional',date:'Audiencia Nacional · 10 ENE 2023',url:SOURCE_FITONOVO_AN},{title:'Casación y ausencia de perjuicio acreditado',date:'Tribunal Supremo · 24 ABR 2025',url:SOURCE_FITONOVO_TS}]},
  marea:{phase:'Sentencia firme tras casación',phaseNote:'El Supremo confirmó o ajustó las penas de los principales responsables por delitos vinculados a adjudicaciones públicas y dádivas.',money:'> 2.000.000 €',moneyLabel:'DÁDIVAS DEL CONJUNTO DE LA TRAMA',moneyNote:'Suma global indicada por el Supremo para las dádivas facilitadas por empresarios. No equivale a una apropiación personal ni al perjuicio público total.',sources:[{title:'Sentencia de instancia e identidades completas',date:'Audiencia Provincial de Asturias · 01 SEP 2017',url:SOURCE_MAREA_AP},{title:'Resolución firme de casación',date:'Tribunal Supremo · 13 SEP 2019',url:SOURCE_MAREA_TS}]},
  ciempozuelos:{phase:'Sentencia firme por falsedad mercantil',phaseNote:'El Supremo condenó a los dos exalcaldes socialistas por confeccionar y remitir un contrato falso a un banco de Andorra.',money:'No determinado',moneyLabel:'DINERO PÚBLICO SUSTRAÍDO',moneyNote:'La sentencia publicada no fija perjuicio público ni apropiación. La casación del fiscal, a la que se adhirió el PSOE, se limitó al delito de falsedad.',sources:[{title:'Condena firme de los dos exalcaldes',date:'Tribunal Supremo · 02 JUN 2016',url:SOURCE_CIEMPOZUELOS}]},
  alicante:{phase:'Dos condenas firmes por prevaricación',phaseNote:'El Supremo confirmó la prevaricación en la contratación fraccionada de Comercio y en el cese arbitrario de una funcionaria interina.',money:'189.762,86 €',moneyLabel:'CONTRATACIÓN EXAMINADA',moneyNote:'Importe acumulado de 25 operaciones menores. Es volumen contractual afectado por la causa, no perjuicio público probado ni enriquecimiento personal.',sources:[{title:'Casación de las dos causas',date:'Tribunal Supremo · 11 MAY 2022',url:SOURCE_ALICANTE_TS},{title:'Identidad completa del exalcalde',date:'Ayuntamiento de Alicante · 27 JUN 2019',url:SOURCE_ECHAVARRI_ID}]},
  malaya:{phase:'Sentencia firme tras casación',phaseNote:'El Supremo confirmó la estructura esencial del macroproceso y redujo a tres años y seis meses la pena de Isabel García Marcos.',money:'No consolidable',moneyLabel:'CUANTÍA PERSONAL EN EL MACROPROCESO',moneyNote:'Los importes de multas, comisos y dádivas publicados para otros condenados o para el conjunto de la causa no se atribuyen a Isabel García Marcos.',sources:[{title:'Sentencia de la Audiencia Provincial',date:'Audiencia Provincial de Málaga · 04 OCT 2013',url:SOURCE_MALAYA_AP},{title:'Resolución firme de casación',date:'Tribunal Supremo · 27 JUL 2015',url:SOURCE_MALAYA_TS}]},
  control_marbella:{phase:'Sentencia de responsabilidad contable',phaseNote:'El Tribunal de Cuentas declaró a María Isabel García Marcos responsable contable directa y ordenó el reintegro. La publicación oficial utilizada informaba de la posibilidad de apelación; no se presenta como condena penal.',money:'71.285,60 €',moneyLabel:'ALCANCE EN FONDOS PÚBLICOS',moneyNote:'Importe declarado como alcance en los fondos de Control de Servicios Locales, S.L. Es una responsabilidad contable diferenciada del caso Malaya.',sources:[{title:'Sentencia 11/2015 de reintegro por alcance',date:'Tribunal de Cuentas / BOE · 16 NOV 2015',url:SOURCE_CONTROL_MARBELLA}]},
  astapa:{phase:'Sentencia de primera instancia con recursos',phaseNote:'La sentencia absolvió a 31 personas y condenó a 15. En enero de 2025 constaba firme para los absueltos y cinco condenados; otros diez, incluido Antonio Barrientos, anunciaron recurso.',money:'No determinado',moneyLabel:'PERJUICIO PÚBLICO PROBADO',moneyNote:'Las fuentes incorporadas no fijan un perjuicio público agregado ni una apropiación personal. La multa de Barrientos se muestra únicamente en su ficha.',sources:[{title:'Constancia oficial del juicio y de la sentencia',date:'CGPJ · ABR 2025',url:SOURCE_ASTAPA_OFFICIAL},{title:'Resumen del fallo de primera instancia',date:'EFE · 08 NOV 2024',url:SOURCE_ASTAPA_EFE},{title:'Firmeza parcial y recursos anunciados',date:'Andalucía Información · 17 ENE 2025',url:SOURCE_ASTAPA_APPEAL}]},
  azud:{phase:'Investigación judicial abierta',phaseNote:'La nota judicial describe una investigación sobre posibles comisiones ilegales ligadas a operaciones urbanísticas y contratos. Los delitos se enumeran para el conjunto, no de forma individual.',money:'300.000–750.000 €',moneyLabel:'COMISIÓN INVESTIGADA · INFORME UCO',moneyNote:'Horquilla atribuida a Rafael Rubio en un informe policial citado por prensa. No es una cantidad declarada probada, una condena ni una estimación judicial de perjuicio público.',sources:[{title:'Investigación y medidas cautelares del caso Azud',date:'TSJ Comunidad Valenciana · 14 MAY 2021',url:SOURCE_AZUD_CGPJ},{title:'Identificación institucional de Rafael Rubio como PSPV-PSOE',date:'TSJ Comunidad Valenciana · 31 JUL 2020',url:SOURCE_RUBIO_AFFILIATION},{title:'Información sobre el informe de la UCO',date:'La Vanguardia · 21 JUN 2025',url:SOURCE_AZUD_UCO}]},
  plus_ultra:{phase:'Investigación judicial abierta',phaseNote:'José Luis Rodríguez Zapatero, Alba Rodríguez y Laura Rodríguez figuran como investigados. No existe sentencia y las hijas fueron incorporadas para garantizar su derecho de defensa sin que el auto concrete delitos para ellas.',money:'53.000.000 €',moneyLabel:'AYUDA PÚBLICA EXAMINADA',moneyNote:'Importe del préstamo público concedido a Plus Ultra. Es el volumen de la operación investigada: no equivale a dinero robado, perjuicio probado ni beneficio personal de los nodos.',sources:[{title:'Auto de investigación de José Luis Rodríguez Zapatero',date:'Audiencia Nacional · 18 MAY 2026',url:SOURCE_PLUS_ULTRA_AUTO},{title:'Auto que amplía las diligencias',date:'Audiencia Nacional · 18 JUN 2026',url:SOURCE_PLUS_ULTRA_DAUGHTERS},{title:'Resumen y cautelas del auto sobre las hijas',date:'EFE · 18 JUN 2026',url:SOURCE_PLUS_ULTRA_EFE}]},
  begona_gomez:{phase:'Continuación del procedimiento con jurado',phaseNote:'La Audiencia Provincial ordenó continuar por presuntos delitos de tráfico de influencias y malversación, y sobreseyó corrupción en los negocios y apropiación indebida. La apertura anterior quedó invalidada al retrotraerse la causa.',money:'No determinado',moneyLabel:'PERJUICIO PÚBLICO PROBADO',moneyNote:'No hay sentencia ni una cuantía de dinero público sustraído declarada probada. Las peticiones de las acusaciones no se presentan como hechos.',sources:[{title:'Estado procesal tras la resolución de la Audiencia',date:'EFE · 18 JUL 2026',url:SOURCE_BEGONA_EFE}]},
  david_sanchez:{phase:'Condena de primera instancia recurrible',phaseNote:'La Audiencia Provincial de Badajoz lo condenó como cooperador necesario de prevaricación administrativa y lo absolvió del resto de infracciones imputadas. Cabe recurso de apelación.',money:'No determinada',moneyLabel:'APROPIACIÓN PERSONAL PROBADA',moneyNote:'La sentencia no hace pronunciamiento de responsabilidad civil ni fija una cantidad apropiada personalmente por David Sánchez.',sources:[{title:'Sentencia 152/2026',date:'Audiencia Provincial de Badajoz · 14 JUL 2026',url:SOURCE_DAVID_SENTENCE}]},
  roldan:{phase:'Sentencia firme y condena cumplida',phaseNote:'El Tribunal Supremo elevó a 31 años la condena por cohecho, falsedad mercantil, malversación, estafa y delitos contra la Hacienda Pública. La documentación oficial posterior trata la liquidación de las responsabilidades.',money:'578.905.000 ptas',moneyLabel:'RESPONSABILIDAD POR MALVERSACIÓN',moneyNote:'Cantidad cuya restitución al Estado se exigía en la ejecutoria, según el auto penitenciario publicado. Se mantiene en pesetas históricas y separada de la indemnización por delitos fiscales y de las multas.',sources:[{title:'Hechos y condena firme en la causa Roldán',date:'Tribunal Constitucional / BOE · 04 JUL 2011',url:SOURCE_ROLDAN_TC},{title:'Condena de 31 años y delitos',date:'RTVE · 24 MAR 2022',url:SOURCE_ROLDAN_RTVE},{title:'Responsabilidad por malversación en la ejecutoria',date:'Audiencia Provincial de Madrid / EL PAÍS · 13 ENE 2005',url:SOURCE_ROLDAN_LIQUIDATION}]},
  urralburu:{phase:'Sentencia firme por cohecho',phaseNote:'El Tribunal Supremo redujo la condena inicial y mantuvo cuatro años de prisión por cohecho. La referencia oficial del CGPJ identifica la STS de 28 de marzo de 2001 como caso Urralburu.',money:'185.000.000 ptas',moneyLabel:'INCREMENTO PATRIMONIAL ATRIBUIDO',moneyNote:'Cifra histórica atribuida a Urralburu en el procedimiento y recogida en la cobertura de la sentencia. No se confunde con la multa inicial de 780 millones ni con los 530 millones repatriados conjuntamente de cuentas suizas.',sources:[{title:'Referencia oficial a la STS 20/2001 · caso Urralburu',date:'CGPJ · Revista del Poder Judicial',url:SOURCE_URRALBURU_TS},{title:'Condena, vinculación socialista y cuantías históricas',date:'elDiario.es Navarra · 07 SEP 2023',url:SOURCE_URRALBURU_HISTORY}]}
};
cases.forEach(item=>Object.assign(item,caseProfiles[item.id]));

const people = [
  { id:'abalos', name:'José Luis Ábalos', role:'Exministro de Transportes y exsecretario de Organización del PSOE', caseIds:['mascarillas','obras'], status:'revision', x:-62,y:-10,z:90,
    charge:'Condenado por organización criminal, cohecho, tráfico de influencias y malversación; nulidad solicitada',
    chargeNote:'El Supremo impuso 24 años y tres meses de prisión y lo absolvió de prevaricación, uso de información privilegiada y falsedad. En julio de 2026 solicitó la nulidad de la sentencia como paso previo a un recurso de amparo.',
    money:'340.000 €', moneyLabel:'PAGOS MENSUALES OBJETO DE COMISO', moneyNote:'Parte principal del comiso conjunto de 430.298 €. La sentencia añade rentas de viviendas y responsabilidad civil compartida; la cifra no debe sumarse otra vez al total del caso.',
    sources:[...sharedMasksSources,...sharedWorksSources] },
  { id:'koldo', name:'Koldo García Izaguirre', role:'Exasesor del Ministerio de Transportes', caseIds:['mascarillas','obras'], status:'revision', x:82,y:-28,z:42,
    charge:'Condenado por organización criminal, cohecho, tráfico de influencias y malversación',
    chargeNote:'El Supremo impuso 19 años y ocho meses de prisión y lo absolvió de prevaricación, uso de información privilegiada y falsedad. La ficha conserva el estado no firme mientras se sustancian las impugnaciones posteriores a la sentencia.',
    money:'43.950,54 €', moneyLabel:'RESPONSABILIDAD CIVIL COMPARTIDA', moneyNote:'Indemnizaciones a Ineco y Tragsatec por contrataciones irregulares. Es responsabilidad civil del fallo, distinta del comiso conjunto de 430.298 € y no una apropiación personal íntegra.',
    sources:[...sharedMasksSources,...sharedWorksSources] },
  { id:'aldama', name:'Víctor de Aldama', role:'Empresario', caseIds:['mascarillas','obras'], status:'revision', x:30,y:-155,z:-12,
    charge:'Condenado por organización criminal y cohecho; ejecución de prisión suspendida por colaboración',
    chargeNote:'El Supremo impuso cuatro años y medio y lo absolvió de inducción a la prevaricación, aprovechamiento de información privilegiada y falsedad. Suspendió la pena de prisión con condiciones por su aportación al descubrimiento de los delitos.',
    money:'72.000 €', moneyLabel:'MULTA PENAL', moneyNote:'Multa impuesta en la sentencia. El comiso de 430.298 € es conjunto para los tres condenados y se muestra en la ficha del caso para evitar duplicaciones.',
    sources:[...sharedMasksSources,...sharedWorksSources] },
  { id:'cerdan', name:'Santos Cerdán', role:'Exsecretario de Organización del PSOE', caseIds:['obras'], status:'investigacion', x:278,y:90,z:-5,
    charge:'Investigado en la pieza de adjudicaciones de obras',
    chargeNote:'La fuente judicial describe posibles delitos de organización criminal, cohecho y tráfico de influencias. La pieza fue remitida al Juzgado Central de Instrucción nº 2 en febrero de 2026.',
    money:'≈ 1 M€', moneyLabel:'FLUJO INVESTIGADO EN LA TRAMA', moneyNote:'El auto alude a un flujo aproximado en la trama, no atribuido íntegramente a esta persona. Los 537,27 M€ citados son volumen de obras adjudicadas, no perjuicio público.',
    sources:[{title:'Auto sobre indicios y medida cautelar',date:'Tribunal Supremo · 23 JUL 2025',url:SOURCE_CERDAN},...sharedWorksSources] },
  { id:'chaves', name:'Manuel Chaves', role:'Expresidente de la Junta de Andalucía', caseIds:['ere'], status:'revision', x:-290,y:65,z:-15,
    charge:'Condena parcialmente anulada; nuevo fallo pendiente',
    chargeNote:'El Tribunal Constitucional estimó parcialmente su amparo por vulneración del derecho a la legalidad penal. La ejecución de los mandatos del TC quedó suspendida al plantearse cuestión prejudicial ante el TJUE.',
    money:'No atribuida', moneyLabel:'CUANTÍA PERSONAL VIGENTE', moneyNote:'Las fuentes consultadas no permiten afirmar una cantidad personalmente sustraída. No se equipara el presupuesto del programa con dinero robado.',
    sources:ereSources },
  { id:'grinan', name:'José Antonio Griñán', role:'Expresidente de la Junta de Andalucía', caseIds:['ere'], status:'revision', x:-120,y:205,z:-70,
    charge:'Condena revisada constitucionalmente; nuevo fallo pendiente',
    chargeNote:'El TC estimó parcialmente el amparo y ordenó retrotraer actuaciones. La Audiencia suspendió la ejecución de ese mandato al elevar una cuestión prejudicial al TJUE.',
    money:'No atribuida', moneyLabel:'CUANTÍA PERSONAL VIGENTE', moneyNote:'No se presenta como “robada” una cifra agregada del sistema de ayudas ni se imputa personalmente una cuantía sin resolución vigente que lo sostenga.',
    sources:[{title:'Nota del TC sobre el amparo de José Antonio Griñán',date:'Tribunal Constitucional · 02 JUL 2024',url:'https://www.tribunalconstitucional.es/NotasDePrensaDocumentos/NP_2024_075/NOTA%20INFORMATIVA%20N%C2%BA%2075-2024.pdf'},ereSources[1]] },
  { id:'perez_sauquillo', name:'Tomás Pérez-Sauquillo', role:'Expresidente de Invercaria', caseIds:['invercaria'], status:'condena', x:330,y:-190,z:-35,
    charge:'Condenado en varias piezas de Invercaria',
    chargeNote:'El Supremo confirmó o dictó condenas por prevaricación y malversación en las piezas de Aceitunas Tatis, Fumapa y retribuciones. Otras piezas terminaron en absolución, por lo que la ficha no generaliza el resultado a todo Invercaria.',
    money:'108.732,22 €', moneyLabel:'RESPONSABILIDAD CIVIL SOLIDARIA', moneyNote:'Indemnización conjunta de la pieza Aceitunas Tatis; no equivale a enriquecimiento personal. La pieza Fumapa trató un préstamo de 300.000 €.',
    sources:[{title:'Condena firme · pieza Aceitunas Tatis',date:'Tribunal Supremo · 20 OCT 2022',url:SOURCE_INVER_TATIS},{title:'Revisión de pena · pieza Fumapa',date:'Tribunal Supremo · 14 MAR 2024',url:SOURCE_INVER_FUMAPA},{title:'Condena · pieza de retribuciones',date:'Tribunal Supremo · 19 SEP 2024',url:SOURCE_INVER_SALARIES}] },
  { id:'faffe_director', name:'Fernando José V.R.', role:'Exdirector general técnico de la FAFFE · identidad abreviada en la fuente', caseIds:['faffe'], status:'revision', x:-335,y:-185,z:-55,
    charge:'Condenado en primera instancia; otras piezas en instrucción',
    chargeNote:'La Audiencia lo condenó por malversación continuada y falsedad documental en la pieza de tarjetas. La resolución publicada permitía apelación; además figura investigado en otra pieza de la FAFFE.',
    money:'24.129 €', moneyLabel:'INDEMNIZACIÓN INDIVIDUAL', moneyNote:'Cantidad a indemnizar a la Junta tras descontar 8.437 € devueltos. Existe además responsabilidad solidaria de 6.300 € con la otra condenada.',
    sources:[{title:'Sentencia de la pieza de tarjetas',date:'Audiencia Provincial de Sevilla · 21 SEP 2023',url:SOURCE_FAFFE},{title:'Otra pieza de FAFFE en instrucción',date:'Juzgado de Instrucción nº 6 · 04 FEB 2025',url:SOURCE_FAFFE_OPEN}] },
  { id:'faffe_financiera', name:'Ana V.R.', role:'Exdirectora económico-financiera de la FAFFE · identidad abreviada', caseIds:['faffe'], status:'revision', x:-175,y:-220,z:-105,
    charge:'Condenada en primera instancia por malversación y falsedad',
    chargeNote:'La Audiencia impuso una condena en la pieza de tarjetas. La fuente subraya que no se acreditó que obtuviera beneficio propio de las conductas probadas.',
    money:'6.300 €', moneyLabel:'RESPONSABILIDAD SOLIDARIA', moneyNote:'Indemnización conjunta vinculada a dos cheques; la sentencia no atribuye beneficio personal a esta persona.',
    sources:[{title:'Sentencia de la pieza de tarjetas',date:'Audiencia Provincial de Sevilla · 21 SEP 2023',url:SOURCE_FAFFE},{title:'Otra pieza de FAFFE en instrucción',date:'Juzgado de Instrucción nº 6 · 04 FEB 2025',url:SOURCE_FAFFE_OPEN}] },
  { id:'mellet', name:'Fernando Mellet', role:'Exdirector general de Mercasevilla', caseIds:['mercasevilla'], status:'condena', x:-50,y:295,z:-95,
    charge:'Condena firme por cohecho',
    chargeNote:'El Supremo confirmó la condena por solicitar, junto al subdirector, un soborno a empresarios a cambio de la gestión de una escuela subvencionada.',
    money:'450.000 €', moneyLabel:'SOBORNO SOLICITADO', moneyNote:'Cantidad solicitada, no dinero público sustraído. La multa confirmada fue de 600.000 € y la subvención vinculada ascendía a 900.000 €.',
    sources:[{title:'Sentencia del caso Mercasevilla',date:'Tribunal Supremo · 03 JUN 2014',url:SOURCE_MERCA}] },
  { id:'ponce', name:'Daniel Ponce', role:'Exsubdirector general de Mercasevilla', caseIds:['mercasevilla'], status:'condena', x:95,y:305,z:-130,
    charge:'Condena firme por cohecho',
    chargeNote:'El Supremo confirmó la condena en relación con la solicitud de soborno a empresarios del grupo La Raza.',
    money:'450.000 €', moneyLabel:'SOLICITUD CONJUNTA DE SOBORNO', moneyNote:'La cifra corresponde a la solicitud conjunta descrita por el Supremo; no debe sumarse por persona ni tratarse como perjuicio público.',
    sources:[{title:'Sentencia del caso Mercasevilla',date:'Tribunal Supremo · 03 JUN 2014',url:SOURCE_MERCA}] },
  { id:'rivas', name:'Antonio Rivas Sánchez', role:'Exdelegado provincial de Empleo de la Junta de Andalucía', caseIds:['mercasevilla'], status:'absuelto', x:45,y:150,z:-80,
    charge:'Absuelto por el Tribunal Supremo',
    chargeNote:'El Supremo anuló su condena al considerar inválida la principal prueba utilizada contra él. La ficha se mantiene para reflejar el resultado exculpatorio y su conexión procesal histórica.',
    money:'0 €', moneyLabel:'RESPONSABILIDAD PENAL ATRIBUIDA', moneyNote:'No existe cuantía atribuible tras la absolución. No se le imputa la solicitud de 450.000 € confirmada para otros condenados.',
    sources:[{title:'Anulación de la condena y absolución',date:'Tribunal Supremo · 03 JUN 2014',url:SOURCE_MERCA}] },
  { id:'navarro_filesa', name:'Carlos Navarro Gómez', role:'Exdiputado del PSOE; condenado en la causa Filesa', caseIds:['filesa'], status:'condena', x:-435,y:5,z:-95,
    charge:'Condenado por falsedad mercantil, asociación ilícita y delito fiscal',
    chargeNote:'El Tribunal Constitucional desestimó su recurso de amparo contra la sentencia del Supremo. La ficha recoge la situación resultante y no atribuye al partido responsabilidad penal distinta de la declarada respecto de las personas.',
    money:'258.827.765 ptas', moneyLabel:'CUOTA FISCAL · RESPONSABILIDAD COMPARTIDA', moneyNote:'Cantidad fijada solidaria y mancomunadamente con otros condenados, además de la multa fiscal. Es una cifra histórica en pesetas y no una cuantía personalmente apropiada.',
    sources:[{title:'STC 123/2001 · recurso de Carlos Navarro',date:'Tribunal Constitucional / BOE · 04 JUN 2001',url:SOURCE_FILESA_NAVARRO}] },
  { id:'sala_filesa', name:'José María Sala i Griso', role:'Exsenador del PSC-PSOE y socio de Time Export', caseIds:['filesa'], status:'condena', x:-315,y:-35,z:-110,
    charge:'Condena por asociación ilícita; falsedad anulada por el TC',
    chargeNote:'El Constitucional anuló exclusivamente la condena por falsedad mercantil al apreciar vulneración de la presunción de inocencia y desestimó el resto del recurso.',
    money:'250.000 ptas', moneyLabel:'MULTA POR ASOCIACIÓN ILÍCITA', moneyNote:'Multa penal histórica, no dinero público sustraído. La condena y multa por falsedad mercantil quedaron anuladas.',
    sources:[{title:'STC 124/2001 · amparo parcial de José María Sala',date:'Tribunal Constitucional / BOE · 04 JUN 2001',url:SOURCE_FILESA_SALA}] },
  { id:'garcia_pretoria', name:'Luis Andrés García Sáez', role:'Exdiputado del PSC', caseIds:['pretoria'], status:'condena', x:305,y:-35,z:-105,
    charge:'Condena firme por tráfico de influencias, prevaricación, cohecho y blanqueo',
    chargeNote:'El Supremo lo absolvió del delito de falsedad y rebajó la pena por cohecho, manteniendo las restantes condenas dictadas por la Audiencia Nacional.',
    money:'5.886.925,66 €', moneyLabel:'GANANCIAS ILÍCITAS / COMISO', moneyNote:'Importe de ganancias ilícitas de las operaciones atribuido por la sentencia de instancia. No representa automáticamente perjuicio presupuestario municipal.',
    sources:[{title:'Sentencia de la Audiencia Nacional',date:'Audiencia Nacional · 30 ABR 2018',url:SOURCE_PRETORIA_AN},{title:'Resolución de casación',date:'Tribunal Supremo · 18 DIC 2020',url:SOURCE_PRETORIA_TS}] },
  { id:'munoz_pretoria', name:'Bartomeu Muñoz', role:'Exalcalde de Santa Coloma de Gramenet por el PSC', caseIds:['pretoria'], status:'condena', x:430,y:85,z:-90,
    charge:'Condena firme por delitos vinculados a operaciones urbanísticas',
    chargeNote:'El Supremo desestimó su recurso y confirmó la pena de cinco años, ocho meses y veintiocho días impuesta por la Audiencia Nacional.',
    money:'1.144.724,55 €', moneyLabel:'DÁDIVAS OBJETO DE COMISO', moneyNote:'Cuantía de las dádivas recibidas cuyo comiso acordó la Audiencia Nacional; no debe sumarse como gasto público directo.',
    sources:[{title:'Sentencia de la Audiencia Nacional',date:'Audiencia Nacional · 30 ABR 2018',url:SOURCE_PRETORIA_AN},{title:'Confirmación de la condena',date:'Tribunal Supremo · 18 DIC 2020',url:SOURCE_PRETORIA_TS}] },
  { id:'fuentes_curbelo', name:'Juan Bernardo Fuentes Curbelo', role:'Exdiputado nacional del PSOE', caseIds:['mediador'], status:'procesamiento', x:-105,y:-240,z:-95,
    charge:'Incluido en el procedimiento abreviado del caso Mediador',
    chargeNote:'La nota judicial confirma que el procedimiento continúa contra 23 personas, entre ellas un exdiputado nacional. No individualiza en esa publicación qué calificación provisional corresponde a cada encausado.',
    money:'No determinada', moneyLabel:'CUANTÍA PERSONAL ATRIBUIBLE', moneyNote:'La resolución pública utilizada no fija una cantidad personalmente sustraída, recibida o malversada por este encausado.',
    sources:[{title:'Finalización de la instrucción',date:'Tribunal de Instancia de Santa Cruz de Tenerife · 12 FEB 2026',url:SOURCE_MEDIADOR_CLOSE},{title:'Identificación en la memoria judicial anual',date:'TSJ de Canarias · Memoria 2023',url:SOURCE_MEDIADOR_NAMES}] },
  { id:'taishet_fuentes', name:'Taishet Fuentes', role:'Exdirector general de Ganadería del Gobierno de Canarias', caseIds:['mediador'], status:'procesamiento', x:105,y:-240,z:-115,
    charge:'Incluido entre los encausados del procedimiento Mediador',
    chargeNote:'La memoria del TSJ identifica su comparecencia ante la instructora. La nota de cierre describe de forma conjunta posibles delitos de cohecho, estafa, malversación, prevaricación, tráfico de influencias, falsedad y blanqueo, sin individualizarlos por persona.',
    money:'No determinada', moneyLabel:'CUANTÍA PERSONAL ATRIBUIBLE', moneyNote:'No se publica en las fuentes incorporadas una cantidad individual que pueda presentarse como perjuicio o enriquecimiento atribuible.',
    sources:[{title:'Finalización de la instrucción',date:'Tribunal de Instancia de Santa Cruz de Tenerife · 12 FEB 2026',url:SOURCE_MEDIADOR_CLOSE},{title:'Comparecencia identificada en memoria judicial',date:'TSJ de Canarias · Memoria 2023',url:SOURCE_MEDIADOR_NAMES}] },
  { id:'juan_fg_linares', name:'Juan F. G.', role:'Exalcalde de Linares y exportavoz del grupo municipal socialista · identidad abreviada por la fuente', caseIds:['linares'], status:'condena', x:-155,y:-125,z:20,
    charge:'Condena firme por malversación de caudales públicos',
    chargeNote:'El Supremo confirmó la condena. Los hechos probados señalan que desvió fondos del grupo municipal mediante cheques al portador y sin justificación documental, actuando sin autorización ni conocimiento del grupo socialista.',
    money:'125.377 €', moneyLabel:'FONDOS PÚBLICOS DESVIADOS', moneyNote:'Cuantía total de los sobresueldos declarados probados durante seis años; en este expediente sí existe una cifra judicialmente atribuida.',
    sources:[{title:'El Supremo confirma la condena por sobresueldos',date:'Tribunal Supremo · 03 JUL 2025',url:SOURCE_LINARES}] },
  { id:'recio_delphi', name:'Manuel Recio Menéndez', role:'Exconsejero de Empleo de la Junta de Andalucía', caseIds:['cursos_delphi'], status:'procesamiento', x:215,y:165,z:55,
    charge:'Procedimiento abreviado por presuntos fraude de subvenciones, prevaricación y malversación',
    chargeNote:'La resolución enumera esos posibles delitos para los tres investigados y no publica una atribución fáctica individual completa. La identidad se cruza con el BOJA, que confirma el nombre del entonces consejero.',
    money:'No determinada', moneyLabel:'CUANTÍA PERSONAL ATRIBUIBLE', moneyNote:'Los 20,24 M€ corresponden a la subvención examinada; la fuente no fija una cantidad personalmente apropiada o malversada por el exconsejero.',
    sources:[{title:'Continuación de la pieza Delphi',date:'Juzgado de Instrucción nº 6 de Sevilla · 14 ENE 2025',url:SOURCE_COURSES_DELPHI},{title:'Identificación del entonces consejero',date:'BOJA · 05 AGO 2010',url:SOURCE_RECIO_ID}] },
  { id:'cuenca_cursos', name:'Francisco Cuenca Rodríguez', role:'Exdelegado provincial y exalcalde de Granada · concejal del PSOE', caseIds:['cursos_inspeccion'], status:'archivo', x:-215,y:165,z:55,
    charge:'Causa archivada respecto de esta persona',
    chargeNote:'El auto de septiembre de 2023 acordó el archivo frente al exalcalde y otras nueve personas. No debe presentarse como acusado en el juicio abierto contra nueve personas distintas.',
    money:'0 €', moneyLabel:'CUANTÍA PENALMENTE ATRIBUIBLE', moneyNote:'Los contratos examinados sumaban 24.412 €, pero la causa quedó archivada respecto de Francisco Cuenca.',
    sources:[{title:'Archivo de la causa respecto del exalcalde',date:'Juzgado de Instrucción nº 6 de Sevilla · 27 SEP 2023',url:SOURCE_COURSES_ARCHIVE},{title:'Identidad y vinculación política',date:'Ayuntamiento de Granada · ficha de transparencia',url:SOURCE_CUENCA_ID}] },
  { id:'riopedre_marea', name:'José Luis Iglesias Riopedre', role:'Exconsejero de Educación del Principado de Asturias', caseIds:['marea'], status:'condena', x:-140,y:70,z:35,
    charge:'Condena firme por prevaricación, falsedad mercantil, fraude a la Administración y cohecho',
    chargeNote:'La Audiencia lo absolvió de malversación, tráfico de influencias y exacciones ilegales. El Supremo ajustó la pena a cinco años y dos meses de prisión.',
    money:'400.000 €', moneyLabel:'MULTA PENAL', moneyNote:'Multa impuesta por la condena; no es una estimación de dinero personalmente apropiado ni del perjuicio total.',
    sources:[{title:'Fallo de la Audiencia Provincial',date:'Audiencia Provincial de Asturias · 01 SEP 2017',url:SOURCE_MAREA_AP},{title:'Casación del caso Marea',date:'Tribunal Supremo · 13 SEP 2019',url:SOURCE_MAREA_TS}] },
  { id:'otero_marea', name:'María Jesús Otero', role:'Exdirectora general de Educación del Principado de Asturias', caseIds:['marea'], status:'condena', x:0,y:70,z:55,
    charge:'Condena firme en el caso Marea',
    chargeNote:'El Supremo fijó una pena de cinco años y cinco meses de prisión. La nota de casación describe conjuntamente delitos de prevaricación, malversación, cohecho y falsedad, sin individualizar en su resumen todos los tipos aplicados a esta condenada.',
    money:'No determinada', moneyLabel:'CUANTÍA PERSONAL ATRIBUIBLE', moneyNote:'La fuente pública incorporada no fija una cantidad individual apropiada, recibida o malversada por esta condenada.',
    sources:[{title:'Fallo e identidad completa',date:'Audiencia Provincial de Asturias · 01 SEP 2017',url:SOURCE_MAREA_AP},{title:'Casación del caso Marea',date:'Tribunal Supremo · 13 SEP 2019',url:SOURCE_MAREA_TS}] },
  { id:'renedo_marea', name:'Marta Renedo Avilés', role:'Exfuncionaria del Principado de Asturias', caseIds:['marea'], status:'condena', x:140,y:70,z:25,
    charge:'Condena firme por delitos vinculados a adjudicaciones a cambio de dádivas',
    chargeNote:'El Supremo confirmó nueve años de prisión. La nota judicial resume conjuntamente prevaricación, malversación, cohecho y falsedad dentro del caso.',
    money:'480.000 €', moneyLabel:'MULTA PENAL', moneyNote:'Multa confirmada por el Supremo; no equivale a la suma personalmente apropiada ni al daño presupuestario total.',
    sources:[{title:'Fallo e identidad completa',date:'Audiencia Provincial de Asturias · 01 SEP 2017',url:SOURCE_MAREA_AP},{title:'Confirmación de condena y multa',date:'Tribunal Supremo · 13 SEP 2019',url:SOURCE_MAREA_TS}] },
  { id:'torrejon_ciempo', name:'Pedro Torrejón', role:'Exalcalde socialista de Ciempozuelos', caseIds:['ciempozuelos'], status:'condena', x:-200,y:-70,z:35,
    charge:'Condena firme por falsedad en documento mercantil',
    chargeNote:'El Supremo consideró probado que participó en la elaboración y envío de un contrato inexistente para justificar ante un banco andorrano el origen de fondos.',
    money:'No determinada', moneyLabel:'CUANTÍA PÚBLICA ATRIBUIBLE', moneyNote:'La resolución no declara una cantidad de dinero público sustraída o dilapidada por este condenado.',
    sources:[{title:'Condena de los exalcaldes de Ciempozuelos',date:'Tribunal Supremo · 02 JUN 2016',url:SOURCE_CIEMPOZUELOS}] },
  { id:'tejeiro_ciempo', name:'Joaquín Tejeiro', role:'Exalcalde socialista de Ciempozuelos', caseIds:['ciempozuelos'], status:'condena', x:0,y:-70,z:55,
    charge:'Condena firme por falsedad en documento mercantil',
    chargeNote:'La sentencia considera que ideó y planificó el contrato falso remitido al banco de Andorra. El recurso del fiscal solo solicitó condena por este delito.',
    money:'No determinada', moneyLabel:'CUANTÍA PÚBLICA ATRIBUIBLE', moneyNote:'La resolución no fija dinero público sustraído o un perjuicio presupuestario personalmente atribuible.',
    sources:[{title:'Condena de los exalcaldes de Ciempozuelos',date:'Tribunal Supremo · 02 JUN 2016',url:SOURCE_CIEMPOZUELOS}] },
  { id:'echavarri_alicante', name:'Gabriel Echávarri', role:'Exalcalde de Alicante por el PSOE', caseIds:['alicante'], status:'condena', x:205,y:80,z:60,
    charge:'Dos condenas firmes por prevaricación administrativa',
    chargeNote:'Una causa se refiere al fraccionamiento deliberado de contratos menores para eludir publicidad y concurrencia; la otra, al cese arbitrario de una funcionaria como represalia. Las penas fueron de ocho años y medio y cuatro años y medio de inhabilitación.',
    money:'No determinada', moneyLabel:'CUANTÍA PERSONAL APROPIADA', moneyNote:'Los 189.762,86 € son el volumen de contratación examinado. La resolución no declara apropiación personal ni fija un perjuicio presupuestario individual.',
    sources:[{title:'Confirmación de ambas condenas',date:'Tribunal Supremo · 11 MAY 2022',url:SOURCE_ALICANTE_TS},{title:'Identidad completa',date:'Ayuntamiento de Alicante · 27 JUN 2019',url:SOURCE_ECHAVARRI_ID}] },
  { id:'garcia_marcos', name:'Isabel García Marcos', role:'Ex primera teniente de alcalde de Marbella y excabeza de lista del PSOE', caseIds:['malaya','control_marbella'], status:'condena', x:365,y:-180,z:60,
    charge:'Condena firme por cohecho pasivo en Malaya; responsabilidad contable en otro procedimiento',
    chargeNote:'El Supremo dejó su pena en tres años y seis meses y la absolvió del delito de alteración de precios. Separadamente, el Tribunal de Cuentas la declaró responsable directa de un alcance en fondos municipales.',
    money:'71.285,60 €', moneyLabel:'ALCANCE EN FONDOS PÚBLICOS', moneyNote:'Cuantía atribuida en el procedimiento contable de Control de Servicios. No se suma con multas o comisos generales de Malaya ni se presenta como enriquecimiento personal probado en esa causa penal.',
    sources:[{title:'Condena en la operación Malaya',date:'Audiencia Provincial de Málaga · 04 OCT 2013',url:SOURCE_MALAYA_AP},{title:'Casación y pena firme',date:'Tribunal Supremo · 27 JUL 2015',url:SOURCE_MALAYA_TS},{title:'Sentencia de responsabilidad contable',date:'Tribunal de Cuentas / BOE · 16 NOV 2015',url:SOURCE_CONTROL_MARBELLA},{title:'Vinculación con la candidatura socialista',date:'Ayuntamiento de Marbella · 12 MAR 2014',url:SOURCE_GARCIA_PSOE}] },
  { id:'antonio_barrientos', name:'Antonio Barrientos', role:'Exalcalde socialista de Estepona', caseIds:['astapa'], status:'revision', x:-360,y:-205,z:40,
    charge:'Condena de primera instancia por cohecho pasivo continuado; recurso anunciado',
    chargeNote:'La Audiencia impuso cinco meses y siete días de suspensión. La condena no se presenta como firme: en enero de 2025 constaba entre las recurridas ante el Tribunal Supremo.',
    money:'40.000 €', moneyLabel:'MULTA PENAL', moneyNote:'Multa impuesta en primera instancia. No es dinero público sustraído ni una apropiación personal acreditada en las fuentes incorporadas.',
    sources:[{title:'Constancia oficial del procedimiento y sentencia',date:'CGPJ · ABR 2025',url:SOURCE_ASTAPA_OFFICIAL},{title:'Fallo y pena individualizada',date:'EFE · 08 NOV 2024',url:SOURCE_ASTAPA_EFE},{title:'Situación del recurso',date:'Andalucía Información · 17 ENE 2025',url:SOURCE_ASTAPA_APPEAL}] },
  { id:'rafael_rubio_azud', name:'Rafael Rubio', role:'Exportavoz del PSPV-PSOE en Valencia y exsubdelegado del Gobierno', caseIds:['azud'], status:'investigacion', x:370,y:170,z:45,
    charge:'Investigado en el caso Azud; delitos descritos de forma conjunta en la causa',
    chargeNote:'La fuente judicial enumera posibles delitos de prevaricación, cohecho, falsedad, blanqueo, tráfico de influencias y asociación ilícita para el conjunto de la investigación, sin individualizarlos en esta nota.',
    money:'300.000–750.000 €', moneyLabel:'COMISIÓN INVESTIGADA · INFORME UCO', moneyNote:'Estimación policial publicada por La Vanguardia. No es un hecho declarado probado ni una cuantía de perjuicio público fijada judicialmente.',
    sources:[{title:'Nota judicial del caso Azud',date:'TSJ Comunidad Valenciana · 14 MAY 2021',url:SOURCE_AZUD_CGPJ},{title:'Identificación institucional y afiliación',date:'TSJ Comunidad Valenciana · 31 JUL 2020',url:SOURCE_RUBIO_AFFILIATION},{title:'Información sobre el informe de la UCO',date:'La Vanguardia · 21 JUN 2025',url:SOURCE_AZUD_UCO}] },
  { id:'zapatero', name:'José Luis Rodríguez Zapatero', role:'Expresidente del Gobierno y ex secretario general del PSOE', caseIds:['plus_ultra'], status:'investigacion', x:-55,y:-270,z:45,
    charge:'Investigado por presunta organización criminal, tráfico de influencias y falsedad documental',
    chargeNote:'El auto atribuye indicios en la fase de instrucción. Zapatero niega haber ejercido influencia y ha solicitado la nulidad de la causa; no existe condena.',
    money:'No determinado', moneyLabel:'BENEFICIO PERSONAL PROBADO', moneyNote:'Los 53 millones corresponden al rescate de la aerolínea y no pueden atribuirse personalmente. No hay una cantidad apropiada declarada probada.',
    sources:[{title:'Auto de investigación',date:'Audiencia Nacional · 18 MAY 2026',url:SOURCE_PLUS_ULTRA_AUTO}] },
  { id:'alba_rodriguez', name:'Alba Rodríguez', role:'Hija de José Luis Rodríguez Zapatero y administradora de What the Fav', caseIds:['plus_ultra'], status:'investigacion', x:-130,y:-315,z:25,
    charge:'Investigada sin delitos individualizados en el auto de incorporación',
    chargeNote:'El instructor acordó darle la condición de investigada para garantizar su defensa por la operativa examinada de la sociedad. Esto no supone acusación ni condena.',
    money:'239.755 €', moneyLabel:'PAGOS A SOCIEDAD INVESTIGADOS', moneyNote:'Importe recibido por la sociedad según el auto resumido por EFE. No es dinero público robado ni beneficio personal declarado probado; no debe duplicarse con la ficha de su hermana.',
    sources:[{title:'Auto de ampliación de diligencias',date:'Audiencia Nacional · 18 JUN 2026',url:SOURCE_PLUS_ULTRA_DAUGHTERS},{title:'Resumen del auto',date:'EFE · 18 JUN 2026',url:SOURCE_PLUS_ULTRA_EFE}] },
  { id:'laura_rodriguez', name:'Laura Rodríguez', role:'Hija de José Luis Rodríguez Zapatero y administradora de What the Fav', caseIds:['plus_ultra'], status:'investigacion', x:70,y:-315,z:30,
    charge:'Investigada sin delitos individualizados en el auto de incorporación',
    chargeNote:'El instructor acordó darle la condición de investigada para garantizar su defensa por la operativa examinada de la sociedad. Esto no supone acusación ni condena.',
    money:'239.755 €', moneyLabel:'PAGOS A SOCIEDAD · CIFRA COMPARTIDA', moneyNote:'La cifra corresponde a la sociedad administrada por ambas hermanas, no a cada una. No es dinero público robado ni beneficio personal declarado probado.',
    sources:[{title:'Auto de ampliación de diligencias',date:'Audiencia Nacional · 18 JUN 2026',url:SOURCE_PLUS_ULTRA_DAUGHTERS},{title:'Resumen del auto',date:'EFE · 18 JUN 2026',url:SOURCE_PLUS_ULTRA_EFE}] },
  { id:'begona', name:'Begoña Gómez', role:'Esposa del presidente del Gobierno', caseIds:['begona_gomez'], status:'procesamiento', x:445,y:-45,z:40,
    charge:'Procedimiento dirigido por presuntos tráfico de influencias y malversación',
    chargeNote:'La Audiencia ordenó continuar únicamente por esos dos delitos y sobreseyó otros dos. La Fiscalía y la defensa solicitan el archivo; no existe condena.',
    money:'No determinada', moneyLabel:'CUANTÍA PÚBLICA ATRIBUIBLE', moneyNote:'No existe una cantidad de dinero público sustraída o dilapidada declarada probada en esta fase.',
    sources:[{title:'Situación procesal y alcance vigente',date:'EFE · 18 JUL 2026',url:SOURCE_BEGONA_EFE}] },
  { id:'david_sanchez_person', name:'David Sánchez Pérez-Castejón', role:'Hermano del presidente del Gobierno y ex alto cargo de la Diputación de Badajoz', caseIds:['david_sanchez'], status:'revision', x:-445,y:25,z:40,
    charge:'Condena de primera instancia por cooperación necesaria en prevaricación administrativa',
    chargeNote:'La sentencia impone nueve años de inhabilitación y lo absuelve del resto de infracciones. Es recurrible ante el TSJ de Extremadura y no se presenta como firme.',
    money:'No determinada', moneyLabel:'APROPIACIÓN PERSONAL PROBADA', moneyNote:'La sentencia no fija responsabilidad civil ni una suma apropiada personalmente por el condenado.',
    sources:[{title:'Sentencia 152/2026 íntegra',date:'Audiencia Provincial de Badajoz · 14 JUL 2026',url:SOURCE_DAVID_SENTENCE}] },
  { id:'luis_roldan', name:'Luis Roldán Ibáñez', role:'Exdirector general de la Guardia Civil y antiguo dirigente socialista', caseIds:['roldan','urralburu'], status:'condena', x:-500,y:-135,z:15,
    charge:'Condena firme por cohecho, falsedad mercantil, malversación, estafa y delitos fiscales',
    chargeNote:'El Tribunal Supremo elevó la condena a 31 años de prisión. Su presencia en el caso Urralburu refleja la conexión procesal navarra documentada, sin mezclar las cuantías de ambos expedientes.',
    money:'578.905.000 ptas', moneyLabel:'RESPONSABILIDAD POR MALVERSACIÓN', moneyNote:'Obligación de restitución al Estado recogida en la ejecutoria. Se mantiene separada de 957.720.504 pesetas por delitos fiscales, multas y otros importes atribuidos al conjunto de las tramas.',
    sources:[{title:'Hechos firmes y conexiones con fondos reservados',date:'Tribunal Constitucional / BOE · 04 JUL 2011',url:SOURCE_ROLDAN_TC},{title:'Condena y trayectoria pública',date:'RTVE · 24 MAR 2022',url:SOURCE_ROLDAN_RTVE},{title:'Responsabilidades económicas en ejecutoria',date:'Audiencia Provincial de Madrid / EL PAÍS · 13 ENE 2005',url:SOURCE_ROLDAN_LIQUIDATION}] },
  { id:'gabriel_urralburu', name:'Gabriel Urralburu Tainta', role:'Expresidente socialista del Gobierno de Navarra y ex secretario general del PSN-PSOE', caseIds:['urralburu'], status:'condena', x:-510,y:185,z:20,
    charge:'Condena firme por cohecho en adjudicaciones de obra pública',
    chargeNote:'El Tribunal Supremo redujo a cuatro años de prisión la condena inicial y mantuvo el cohecho. La ficha no conserva como vigentes los dos delitos fiscales anulados al considerarlos incompatibles con el origen ilícito de las ganancias.',
    money:'185.000.000 ptas', moneyLabel:'INCREMENTO PATRIMONIAL ATRIBUIDO', moneyNote:'Cifra histórica atribuida personalmente en el procedimiento. No se suma con la multa inicial posteriormente revisada ni con fondos repatriados conjuntamente desde cuentas de varios condenados.',
    sources:[{title:'Referencia oficial a la STS 20/2001',date:'CGPJ · Revista del Poder Judicial',url:SOURCE_URRALBURU_TS},{title:'Sentencia, afiliación y cuantías del caso',date:'elDiario.es Navarra · 07 SEP 2023',url:SOURCE_URRALBURU_HISTORY}] }
].map(p=>({...p,kind:'person',initials:p.name.split(' ').map(s=>s[0]).slice(0,2).join('').toUpperCase()}));

const entities = [
  { id:'psoe_fitonovo', name:'PSOE', role:'Formación política · partícipe a título lucrativo en la pieza Fitonovo', caseIds:['fitonovo'], status:'absuelto', x:190,y:-65,z:40,
    charge:'Absuelto como partícipe a título lucrativo',
    chargeNote:'La Audiencia Nacional rechazó la pretensión de responsabilidad civil formulada contra el PSOE. Este nodo representa una persona jurídica, no una persona investigada o condenada.',
    money:'0 €', moneyLabel:'RESPONSABILIDAD IMPUESTA', moneyNote:'La sentencia absolvió a la formación política de la reclamación planteada en esta pieza.',
    sources:[{title:'Absolución del PSOE e IU como partícipes lucrativos',date:'Audiencia Nacional · 10 ENE 2023',url:SOURCE_FITONOVO_AN}] }
].map(entity=>({...entity,kind:'entity',initials:'PS'}));
const actors=[...people,...entities];
cases.forEach(c=>c.count=actors.filter(actor=>actor.caseIds.includes(c.id)).length);
const nodes=[...cases.map(c=>({...c,kind:'case'})),...actors];
const links=[];
actors.forEach(actor=>actor.caseIds.forEach(caseId=>links.push({a:actor.id,b:caseId,type:actor.kind==='entity'?'participación jurídica':'vinculación procesal'})));
[
  {a:'abalos',b:'koldo',type:'Coacusados en la pieza de mascarillas'},
  {a:'abalos',b:'aldama',type:'Coacusados en la pieza de mascarillas'},
  {a:'koldo',b:'aldama',type:'Coacusados en la pieza de mascarillas'},
  {a:'cerdan',b:'abalos',type:'Coinciden en la pieza de obras públicas'},
  {a:'cerdan',b:'koldo',type:'Coinciden en la pieza de obras públicas'},
  {a:'cerdan',b:'aldama',type:'Coinciden en la pieza de obras públicas'},
  {a:'faffe_director',b:'faffe_financiera',type:'Enjuiciados en la pieza de tarjetas FAFFE'},
  {a:'mellet',b:'ponce',type:'Enjuiciados en la pieza Mercasevilla'},
  {a:'mellet',b:'rivas',type:'Enjuiciados en la misma pieza; Rivas fue absuelto'},
  {a:'ponce',b:'rivas',type:'Enjuiciados en la misma pieza; Rivas fue absuelto'},
  {a:'navarro_filesa',b:'sala_filesa',type:'Condenados en la causa Filesa'},
  {a:'garcia_pretoria',b:'munoz_pretoria',type:'Condenados en la operación Pretoria'},
  {a:'fuentes_curbelo',b:'taishet_fuentes',type:'Encausados en el procedimiento Mediador'}
  ,{a:'riopedre_marea',b:'otero_marea',type:'Condenados en el caso Marea'}
  ,{a:'riopedre_marea',b:'renedo_marea',type:'Condenados en el caso Marea'}
  ,{a:'otero_marea',b:'renedo_marea',type:'Condenadas en el caso Marea'}
  ,{a:'torrejon_ciempo',b:'tejeiro_ciempo',type:'Condenados por el mismo contrato falso'}
  ,{a:'luis_roldan',b:'gabriel_urralburu',type:'Coincidieron en la trama navarra de adjudicaciones y comisiones'}
].forEach(relation=>links.push(relation));

const canvas=document.querySelector('#networkCanvas'), ctx=canvas.getContext('2d'), wrap=document.querySelector('#canvasWrap');
const state={rotX:-.08,rotY:.08,zoom:1,drag:false,lastX:0,lastY:0,startX:0,startY:0,hover:null,selected:'abalos',filter:'all',query:'',caseFocus:null};
let dpr=1, projected=[];

function resize(){dpr=Math.min(window.devicePixelRatio||1,2);const r=wrap.getBoundingClientRect();canvas.width=r.width*dpr;canvas.height=r.height*dpr;canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function transform(n){const cy=Math.cos(state.rotY),sy=Math.sin(state.rotY),cx=Math.cos(state.rotX),sx=Math.sin(state.rotX);let x=n.x*cy-n.z*sy,z=n.x*sy+n.z*cy,y=n.y*cx-z*sx;z=n.y*sx+z*cx;const perspective=720/(720+z);return{...n,sx:wrap.clientWidth/2+x*perspective*state.zoom,sy:wrap.clientHeight/2+y*perspective*state.zoom,scale:perspective*state.zoom,depth:z}}
function searchableText(n){return[n.name,n.subtitle,n.role,n.charge,n.chargeNote,n.phase,n.phaseNote,n.moneyLabel,n.moneyNote].filter(Boolean).join(' ').toLowerCase()}
function visible(n){if(state.filter!=='all'&&n.status!==state.filter)return false;if(state.query&&!searchableText(n).includes(state.query))return false;if(state.caseFocus&&n.id!==state.caseFocus&&!(n.caseIds||[]).includes(state.caseFocus))return false;return true}
function activeIds(){if(!state.selected)return new Set();const selected=nodes.find(node=>node.id===state.selected),ids=new Set([state.selected]);if(!selected)return ids;if(selected.kind==='case'){actors.filter(actor=>actor.caseIds.includes(selected.id)).forEach(actor=>ids.add(actor.id));return ids}selected.caseIds.forEach(caseId=>ids.add(caseId));actors.filter(actor=>actor.id!==selected.id&&actor.caseIds.some(caseId=>selected.caseIds.includes(caseId))).forEach(actor=>ids.add(actor.id));links.forEach(link=>{if(link.a===selected.id)ids.add(link.b);if(link.b===selected.id)ids.add(link.a)});return ids}
function draw(){ctx.clearRect(0,0,wrap.clientWidth,wrap.clientHeight);projected=nodes.filter(visible).map(transform).sort((a,b)=>a.depth-b.depth);const pmap=new Map(projected.map(p=>[p.id,p])),active=activeIds();links.forEach(l=>{const a=pmap.get(l.a),b=pmap.get(l.b);if(!a||!b)return;const hi=state.selected&&active.has(l.a)&&active.has(l.b);ctx.beginPath();ctx.moveTo(a.sx,a.sy);ctx.lineTo(b.sx,b.sy);ctx.strokeStyle=hi?'rgba(127,231,242,.82)':'rgba(87,116,132,.2)';ctx.lineWidth=hi?1.45:.7;ctx.shadowColor=hi?'#7fe7f2':'transparent';ctx.shadowBlur=hi?9:0;ctx.stroke();ctx.shadowBlur=0});projected.forEach(n=>drawNode(n,active));document.querySelector('#emptyState').hidden=projected.length>0}
function drawNode(n,active){const isCase=n.kind==='case',isEntity=n.kind==='entity',selected=n.id===state.selected,dim=state.selected&&!active.has(n.id)&&!selected,r=(isCase?16:isEntity?10:8)*Math.max(.72,n.scale);ctx.save();ctx.globalAlpha=dim?.22:1;if(isCase){ctx.beginPath();ctx.arc(n.sx,n.sy,r+9,0,Math.PI*2);ctx.strokeStyle=n.color+'42';ctx.lineWidth=1;ctx.setLineDash([2,4]);ctx.stroke();ctx.setLineDash([])}const glow=ctx.createRadialGradient(n.sx,n.sy,0,n.sx,n.sy,r*3);glow.addColorStop(0,isCase?n.color+'78':isEntity?'#f07bc177':'#7fe7f292');glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(n.sx,n.sy,r*3,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(n.sx,n.sy,r,0,Math.PI*2);ctx.fillStyle=isCase?'#0c151d':isEntity?'#211627':selected?'#d2fbfd':'#8edee7';ctx.fill();ctx.strokeStyle=isCase?n.color:isEntity?'#f07bc1':selected?'#fff':'#b9f4f8';ctx.lineWidth=isCase||isEntity?1.2:1;ctx.stroke();if(isCase||isEntity){ctx.beginPath();ctx.arc(n.sx,n.sy,r-(isCase?5:3),0,Math.PI*2);ctx.strokeStyle=(isCase?n.color:'#f07bc1')+'a0';ctx.stroke()}if(selected){ctx.beginPath();ctx.arc(n.sx,n.sy,r+7+Math.sin(Date.now()/300)*1.5,0,Math.PI*2);ctx.strokeStyle='rgba(127,231,242,.5)';ctx.stroke()}if(isCase||selected||state.hover===n.id||active.has(n.id)){ctx.font=`${isCase?'650':'500'} ${isCase?10:8}px Inter, sans-serif`;ctx.textAlign='center';ctx.fillStyle=dim?'#586471':'#dce5e9';ctx.shadowColor='#070a0f';ctx.shadowBlur=5;ctx.fillText(n.name,n.sx,n.sy+r+(isCase?19:14));ctx.shadowBlur=0}ctx.restore()}
function hit(x,y){return[...projected].reverse().find(n=>Math.hypot(x-n.sx,y-n.sy)<(n.kind==='case'?25:15))}

canvas.addEventListener('pointerdown',e=>{state.drag=true;state.startX=state.lastX=e.clientX;state.startY=state.lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(state.drag){state.rotY+=(e.clientX-state.lastX)*.006;state.rotX+=(e.clientY-state.lastY)*.004;state.lastX=e.clientX;state.lastY=e.clientY;draw();return}const n=hit(x,y);state.hover=n?.id||null;canvas.style.cursor=n?'pointer':'grab';const card=document.querySelector('#hoverCard');if(n){card.hidden=false;card.style.left=(x+14)+'px';card.style.top=(y+12)+'px';card.innerHTML=`<strong>${n.name}</strong><span>${n.subtitle||n.role}</span>`}else card.hidden=true;draw()});
canvas.addEventListener('pointerup',e=>{const moved=Math.abs(e.clientX-state.startX)+Math.abs(e.clientY-state.startY);state.drag=false;if(moved<5){const r=canvas.getBoundingClientRect(),n=hit(e.clientX-r.left,e.clientY-r.top);if(n)selectNode(n.id)}});
canvas.addEventListener('pointerleave',()=>{state.drag=false;state.hover=null;document.querySelector('#hoverCard').hidden=true;draw()});
canvas.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.55,Math.min(2,state.zoom*(e.deltaY>0?.92:1.08)));draw()},{passive:false});

function syncUrl(id){try{const url=new URL(location.href);if(id)url.searchParams.set('node',id);else url.searchParams.delete('node');history.replaceState({},'',url)}catch{}}
function selectNode(id,{sync=true}={}){const n=nodes.find(x=>x.id===id);if(!n)return;if(n.kind==='case'){state.caseFocus=id;state.selected=id;document.querySelectorAll('.case-item').forEach(b=>b.classList.toggle('active',b.dataset.id===id));updateCaseDetail(n);if(sync)syncUrl(id);draw();return}state.caseFocus=null;state.selected=id;document.querySelectorAll('.case-item').forEach(b=>b.classList.remove('active'));updateDetail(n);if(sync)syncUrl(id);draw()}
function applyStatus(status){const labels={investigacion:'EN INVESTIGACIÓN',procesamiento:'PROCEDIMIENTO ABREVIADO',juicio:'JUICIO ABIERTO',revision:'EN REVISIÓN / NO FIRME',condena:'SENTENCIA FIRME',absuelto:'ABSUELTO',archivo:'ARCHIVADO / SOBRESEÍDO'},colors={investigacion:'var(--amber)',procesamiento:'#42c7aa',juicio:'var(--violet)',revision:'#6c8cff',condena:'var(--red)',absuelto:'#64d18f',archivo:'#8aa0b5'},badge=document.querySelector('#statusBadge');badge.innerHTML=`<i></i> ${labels[status]}`;badge.style.color=colors[status]}
function renderSources(sources){document.querySelector('#sourceCount').textContent=sources.length;document.querySelector('#sources').innerHTML=sources.map(s=>`<div class="source-entry"><strong>${s.title}</strong><span>${s.date}</span><a href="${s.url}" target="_blank" rel="noreferrer">Abrir fuente ↗</a></div>`).join('')}
function classifyMoney(value,label){const text=`${value} ${label}`.toUpperCase();if(/^0(?:[,.]|\s|€)/.test(String(value).trim()))return'SIN RESPONSABILIDAD ECONÓMICA';if(/NO DETERMIN|NO ACREDIT|NO CONSOLID|POR PIEZA|^—/.test(text))return'NO SUMABLE / NO DETERMINADA';if(/MULTA/.test(text))return'MULTA PENAL';if(/COMISO|GANANCIAS|DÁDIVAS|EFECTIVO|SOBORNO|COMISIÓN/.test(text))return'DÁDIVA · GANANCIA · COMISO';if(/CONTRAT|SUBVENCIÓN|FLUJO/.test(text))return'VOLUMEN EXAMINADO';if(/PERJUICIO|FONDOS PÚBLICOS DESVIADOS/.test(text))return'PERJUICIO / FONDOS PÚBLICOS';return'CUANTÍA DOCUMENTADA'}
function applyMoney(value,label,note){document.querySelector('#moneyValue').textContent=value;document.querySelector('#moneyLabel').textContent=label;document.querySelector('#moneyNote').textContent=note;document.querySelector('#moneyKind').textContent=classifyMoney(value,label)}
function relationshipRows(actor){return actors.filter(other=>other.id!==actor.id&&other.caseIds.some(caseId=>actor.caseIds.includes(caseId))).map(other=>{const direct=links.find(link=>(link.a===actor.id&&link.b===other.id)||(link.b===actor.id&&link.a===other.id));const shared=actor.caseIds.filter(caseId=>other.caseIds.includes(caseId)).map(caseId=>cases.find(item=>item.id===caseId)?.name).filter(Boolean);return{actor:other,label:direct?.type||`Coincidencia procesal en ${shared.join(' y ')}`,direct:Boolean(direct)}}).sort((a,b)=>Number(b.direct)-Number(a.direct)||a.actor.name.localeCompare(b.actor.name,'es'))}
function updateDetail(p){document.querySelector('#relationSectionTitle').textContent='TRAMA VINCULADA';document.querySelector('#processSectionTitle').textContent='SITUACIÓN PROCESAL';document.querySelector('#moneySectionTitle').textContent='CUANTÍA ATRIBUIBLE';document.querySelector('#avatar').textContent=p.initials;document.querySelector('#personName').textContent=p.name;document.querySelector('#personRole').textContent=p.role;applyStatus(p.status);const linkedCases=p.caseIds.map(id=>cases.find(c=>c.id===id));document.querySelector('#linkedCases').innerHTML=linkedCases.map(c=>`<button class="linked-case" data-case="${c.id}"><span class="mini-orbit" style="color:${c.color};border-color:${c.color}55">◌</span><span><strong>${c.name}</strong><small>${c.subtitle}</small></span><b>›</b></button>`).join('');document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>selectNode(b.dataset.case));document.querySelector('#chargeCard').innerHTML=`<span class="charge-icon">§</span><div><strong>${p.charge}</strong><p>${p.chargeNote}</p></div>`;applyMoney(p.money,p.moneyLabel,p.moneyNote);const related=relationshipRows(p);document.querySelector('#connectionCount').textContent=related.length;document.querySelector('#connections').innerHTML=related.length?related.map(({actor,label,direct})=>`<button class="connection ${direct?'direct':'shared'}" data-person="${actor.id}"><i>${actor.initials}</i><span><strong>${actor.name}</strong><small>${direct?'VÍNCULO DOCUMENTADO':'MISMA TRAMA'} · ${label}</small></span></button>`).join(''):'<p class="placeholder">No hay otros actores publicados en esta pieza.</p>';document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>selectNode(b.dataset.person));renderSources(p.sources)}
function updateCaseDetail(c){const participants=actors.filter(actor=>actor.caseIds.includes(c.id));document.querySelector('#relationSectionTitle').textContent='ACTORES VINCULADOS';document.querySelector('#processSectionTitle').textContent='ESTADO DE LA TRAMA';document.querySelector('#moneySectionTitle').textContent='ALCANCE ECONÓMICO';document.querySelector('#avatar').textContent='◎';document.querySelector('#personName').textContent=c.name;document.querySelector('#personRole').textContent=c.subtitle;applyStatus(c.status);document.querySelector('#linkedCases').innerHTML=participants.map(p=>`<button class="linked-case" data-person="${p.id}"><span class="mini-orbit" style="color:${p.kind==='entity'?'#f07bc1':c.color};border-color:${p.kind==='entity'?'#f07bc155':c.color+'55'}">${p.initials}</span><span><strong>${p.name}</strong><small>${p.role}</small></span><b>›</b></button>`).join('');document.querySelector('#chargeCard').innerHTML=`<span class="charge-icon">§</span><div><strong>${c.phase}</strong><p>${c.phaseNote}</p></div>`;applyMoney(c.money,c.moneyLabel,c.moneyNote);document.querySelector('#connectionCount').textContent=participants.length;document.querySelector('#connections').innerHTML=participants.map(p=>`<button class="connection" data-person="${p.id}"><i>${p.initials}</i><span><strong>${p.name}</strong><small>${p.kind==='entity'?'ENTIDAD · ':''}${p.status.toUpperCase()}</small></span></button>`).join('');document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>selectNode(b.dataset.person));renderSources(c.sources)}
function buildCases(){document.querySelector('#caseList').innerHTML=cases.map(c=>`<button class="case-item" data-id="${c.id}" style="--case-color:${c.color}"><span class="case-orbit">◌</span><span><strong>${c.name}</strong><small>${c.subtitle}</small></span><b>${c.count}</b></button>`).join('');document.querySelectorAll('.case-item').forEach(b=>b.onclick=()=>selectNode(b.dataset.id))}
function refreshCatalogMetrics(){document.querySelectorAll('.filter').forEach(button=>{const value=button.dataset.filter;button.querySelector('b').textContent=value==='all'?actors.length:actors.filter(actor=>actor.status===value).length});document.querySelector('#caseTotal').textContent=cases.length;document.querySelector('#peopleMetric').textContent=people.length;document.querySelector('#caseMetric').textContent=cases.length;document.querySelector('#linkMetric').textContent=links.length}
function buildTimeline(){const ordered=[...cases].sort((a,b)=>b.milestoneDate.localeCompare(a.milestoneDate));document.querySelector('#timelineView').innerHTML=`<div class="timeline-title"><div class="eyebrow">HITOS JUDICIALES VERIFICADOS</div><h2>La red a través del tiempo</h2><p>Cada fecha representa el último hito incorporado, no el inicio del caso.</p></div><div class="timeline-track">${ordered.map(c=>`<article class="timeline-entry" data-timeline-case="${c.id}" style="--event-color:${c.color}"><span class="timeline-year">${c.milestoneDate.slice(0,4)}</span><strong>${c.name}</strong><p>${c.milestone}</p><small>${c.milestoneDate.split('-').reverse().join(' · ')} · ${c.count} ACTOR${c.count===1?'':'ES'}</small></article>`).join('')}</div>`;document.querySelectorAll('[data-timeline-case]').forEach(entry=>entry.onclick=()=>{setView('network');selectNode(entry.dataset.timelineCase)})}
function setView(view){const timeline=view==='timeline';document.querySelector('#timelineView').hidden=!timeline;canvas.hidden=timeline;document.querySelector('.canvas-hint').hidden=timeline;document.querySelector('.legend').hidden=timeline;document.querySelector('.zoom-tools').hidden=timeline;document.querySelectorAll('.view-switch button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(!timeline)resize()}

document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;state.caseFocus=null;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.case-item').forEach(x=>x.classList.remove('active'));draw()});
document.querySelector('#clearFilters').onclick=()=>{state.filter='all';state.query='';state.caseFocus=null;document.querySelector('#searchInput').value='';document.querySelectorAll('.filter').forEach((x,i)=>x.classList.toggle('active',i===0));document.querySelectorAll('.case-item').forEach(x=>x.classList.remove('active'));draw()};
document.querySelector('#searchInput').addEventListener('input',e=>{state.query=e.target.value.trim().toLowerCase();draw()});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('#searchInput').focus()}if(e.key==='Escape'){document.querySelector('#modal').hidden=true;document.querySelector('#coverageModal').hidden=true}});
document.querySelector('#zoomIn').onclick=()=>{state.zoom=Math.min(2,state.zoom*1.16);draw()};document.querySelector('#zoomOut').onclick=()=>{state.zoom=Math.max(.55,state.zoom/1.16);draw()};document.querySelector('#resetView').onclick=()=>{state.rotX=-.08;state.rotY=.08;state.zoom=1;state.caseFocus=null;draw()};
document.querySelectorAll('.detail-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.detail-tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab-content').forEach(x=>x.classList.toggle('active',x.id===`tab-${b.dataset.tab}`))});
document.querySelectorAll('.view-switch button').forEach(b=>b.onclick=()=>setView(b.dataset.view));
const modal=document.querySelector('#modal');document.querySelector('#aboutButton').onclick=()=>modal.hidden=false;document.querySelector('#modalClose').onclick=()=>modal.hidden=true;modal.onclick=e=>{if(e.target===modal)modal.hidden=true};
const coverageModal=document.querySelector('#coverageModal');document.querySelector('#coverageButton').onclick=()=>coverageModal.hidden=false;document.querySelector('#coverageClose').onclick=()=>coverageModal.hidden=true;coverageModal.onclick=e=>{if(e.target===coverageModal)coverageModal.hidden=true};
document.querySelector('#shareButton').onclick=async()=>{const url=location.href;try{await navigator.clipboard.writeText(url);const b=document.querySelector('#shareButton');b.innerHTML='<span>✓</span> Enlace copiado';setTimeout(()=>b.innerHTML='<span>↗</span> Compartir vista',1600)}catch{prompt('Copia este enlace para conservar la selección:',url)}};
document.querySelector('#closeDetail').onclick=()=>{state.selected=null;state.caseFocus=null;syncUrl(null);document.querySelectorAll('.case-item').forEach(b=>b.classList.remove('active'));draw()};
buildCases();buildTimeline();refreshCatalogMetrics();document.querySelector('#coverageCases').textContent=cases.length;document.querySelector('#coverageActors').textContent=actors.length;const requestedNode=new URL(location.href).searchParams.get('node');if(requestedNode&&nodes.some(node=>node.id===requestedNode))selectNode(requestedNode,{sync:false});else updateDetail(people[0]);window.addEventListener('resize',resize);resize();
function animate(){draw();requestAnimationFrame(animate)}requestAnimationFrame(animate);
